"""
English System API。對應 public."English_System" 表（測試文章；欄位與 DDL 一致）：
  system_id（bigint generated by default as identity PK）、system_tab_id、system_name、person_id、
  file_metadata、quiz_type（smallint NOT NULL 預設 0）、quiz_text、quiz_mp3_filename、quiz_youtube、
  system_prompt_instruction、system_metadata、local、deleted、updated_at、created_at。
  表啟用 RLS（Row Level Security）；後端以 service_role 寫入時不受 RLS 限制。

- GET /english_system/tabs：僅 deleted=false；person_id 與 query 相同；local 篩選（未傳則依連線是否本機）；依 created_at 舊→新（對齊 GET /rag/tabs）。
- GET /english_system/tab/for-exam：依 System_Setting 讀取 system_id（本機／deploy key），取得該筆 English_System（deleted=false）。
- POST /english_system/tab/create：對齊 POST /rag/tab/create（system_tab_id、tab_name→system_name、person_id、local）。
- PUT /english_system/tab/tab-name：對齊 PUT /rag/tab/tab-name（system_id、tab_name→system_name）；僅 deleted=false。
- POST /english_system/transcript/audio：上傳 MP3／音訊（Form 必填 system_tab_id）；若尚無該 system_tab_id 之 English_System 列則自動建立一筆（system_name 預設為上傳檔之主檔名，local 依連線判定）。先寫入 Supabase Storage（SUPABASE_ENGLISH_BUCKET，預設 english_system）路徑對齊 RAG：{person_id}/{system_tab_id}/upload/…，再以 **Deepgram** 預錄 API 轉逐字稿（API Key：環境變數 DEEPGRAM_API_KEY 或 System_Setting key=deepgram_api_key；可選 DEEPGRAM_MODEL 預設 nova-2），並更新 English_System.file_metadata、quiz_mp3_filename、quiz_text。
- GET /english_system/transcript/youtube：以 video_id 或 YouTube 網址擷取字幕為純文字（query：languages 逗號分隔，預設 en）。
"""

import logging
import os
from pathlib import Path
from typing import Any

from fastapi import APIRouter, File, Form, HTTPException, Query, Request, UploadFile

from dependencies.person_id import PersonId
from pydantic import BaseModel, Field
from youtube_transcript_api._errors import (
    InvalidVideoId,
    NoTranscriptFound,
    TranscriptsDisabled,
    VideoUnavailable,
    YouTubeTranscriptApiException,
)

from utils.datetime_utils import now_taipei_iso, to_taipei_iso
from utils.english_system_exam_setting import fetch_exam_english_system_id_from_settings
from utils.english_system_storage import save_english_system_upload_audio
from utils.english_system_transcript import (
    parse_youtube_video_id,
    transcribe_audio_bytes_deepgram,
    youtube_transcript_plain_text,
)
from utils.json_utils import to_json_safe
from utils.rag_exam_setting import is_localhost_request
from utils.supabase_client import get_supabase

router = APIRouter(prefix="/english_system", tags=["english system"])


def _english_system_table_select(
    *,
    exclude_deleted: bool = True,
    local_match: bool | None = None,
) -> list[dict[str, Any]]:
    """查詢 English_System。exclude_deleted 時僅 deleted=false。local_match 指定時僅回傳該 local。依 created_at 升序。"""
    supabase = get_supabase()
    q = supabase.table("English_System").select("*")
    if exclude_deleted:
        q = q.eq("deleted", False)
    if local_match is not None:
        q = q.eq("local", local_match)
    q = q.order("created_at", desc=False)
    resp = q.execute()
    return resp.data or []


class ListEnglishSystemResponse(BaseModel):
    """GET /english_system/tabs。"""

    english_systems: list[dict] = Field(..., description="English_System 表列")
    count: int


class CreateEnglishSystemRequest(BaseModel):
    """POST /english_system/tab/create：對齊 Rag 之 tab 識別／顯示名／person_id／local。"""

    system_tab_id: str = Field(..., description="English_System.system_tab_id（對齊 Rag.rag_tab_id）")
    tab_name: str = Field(..., description="顯示名稱，寫入 English_System.system_name（對齊 Rag.tab_name）")
    person_id: str = Field(..., description="使用者識別，寫入 English_System.person_id")
    local: bool = Field(False, description="是否為本機列，寫入 English_System.local")


class TranscriptAudioResponse(BaseModel):
    """POST /english_system/transcript/audio 回傳。"""

    text: str = Field(..., description="Deepgram 轉錄全文")
    elapsed_seconds: float = Field(..., description="自開始呼叫 Deepgram 至完成之秒數")
    model: str = Field(..., description="Deepgram model（環境變數 DEEPGRAM_MODEL，預設 nova-2）")
    filename: str | None = Field(None, description="原始上傳檔名")
    bucket: str = Field(..., description="Supabase Storage bucket 名稱")
    storage_path: str = Field(..., description="Storage 物件路徑")


class TranscriptYoutubeResponse(BaseModel):
    """GET /english_system/transcript/youtube 回傳。"""

    text: str = Field(..., description="字幕合併後之全文")
    elapsed_seconds: float = Field(..., description="擷取耗時（秒）")
    video_id: str = Field(..., description="解析後之 YouTube video_id")


_AUDIO_SUFFIX_OK = frozenset({
    ".mp3", ".wav", ".m4a", ".webm", ".ogg", ".flac", ".opus", ".mp4", ".mpeg", ".mpga", ".aac", ".wma",
})


class UpdateEnglishSystemUnitNameRequest(BaseModel):
    """PUT /english_system/tab/tab-name：請求僅含 system_id（主鍵）、tab_name；勿傳 system_tab_id。"""

    system_id: int = Field(
        ...,
        description="English_System 主鍵，與 POST /english_system/tab/create 回傳之 system_id 相同",
    )
    tab_name: str = Field(
        ...,
        description="新的顯示名稱，寫入 English_System.system_name（對齊 Rag.tab_name）",
    )


def _english_system_default_row(
    system_tab_id: str,
    *,
    system_name: str = "",
    person_id: str = "",
    local: bool = False,
) -> dict[str, Any]:
    """English_System 新增一筆（不含 system_id，由 identity 產生）。"""
    ts = now_taipei_iso()
    return {
        "system_tab_id": system_tab_id,
        "system_name": system_name if system_name is not None else "",
        "person_id": person_id if person_id is not None else "",
        "file_metadata": None,
        "quiz_type": 0,
        "quiz_text": None,
        "quiz_mp3_filename": None,
        "quiz_youtube": None,
        "system_prompt_instruction": None,
        "system_metadata": None,
        "local": local,
        "deleted": False,
        "created_at": ts,
        "updated_at": ts,
    }


def _empty_for_exam_english_system() -> dict[str, Any]:
    """未設定或查無列時回傳（鍵與 English_System 表欄位一致，值皆 null）。"""
    return {
        "system_id": None,
        "system_tab_id": None,
        "system_name": None,
        "person_id": None,
        "file_metadata": None,
        "quiz_type": None,
        "quiz_text": None,
        "quiz_mp3_filename": None,
        "quiz_youtube": None,
        "system_prompt_instruction": None,
        "system_metadata": None,
        "local": None,
        "deleted": None,
        "updated_at": None,
        "created_at": None,
    }


@router.get("/tabs", response_model=ListEnglishSystemResponse)
def list_english_system_tabs(
    request: Request,
    person_id: PersonId,
    local: bool | None = Query(
        None,
        description="僅回傳 English_System.local 與此值相同之列。未傳時依連線是否本機判定（對齊 GET /rag/tabs）",
    ),
):
    """
    列出 English_System，僅 deleted=false，且 person_id 與 query 相同；local 篩選同 GET /rag/tabs。
    回傳依 created_at 舊→新。
    """
    try:
        local_filter = local if local is not None else is_localhost_request(request)
        data = _english_system_table_select(exclude_deleted=True, local_match=local_filter)
        pid = person_id.strip()
        data = [r for r in data if (r.get("person_id") or "").strip() == pid]
        data = to_json_safe(data)
        return ListEnglishSystemResponse(english_systems=data, count=len(data))
    except Exception as e:
        logging.exception("GET /english_system/tabs 錯誤")
        raise HTTPException(status_code=500, detail=f"列出 English_System 失敗: {e!s}")


@router.get("/tab/for-exam")
def get_for_exam_english_system(request: Request, _person_id: PersonId):
    """
    依連線讀取 System_Setting 的 value 作為 system_id，取得 English_System（deleted=false）。
    """
    try:
        supabase = get_supabase()
        _, sid = fetch_exam_english_system_id_from_settings(supabase, request)
        if sid is None or sid <= 0:
            return _empty_for_exam_english_system()
        resp = (
            supabase.table("English_System")
            .select("*")
            .eq("system_id", sid)
            .eq("deleted", False)
            .limit(1)
            .execute()
        )
        data = resp.data or []
        if len(data) == 0:
            return _empty_for_exam_english_system()
        return to_json_safe(data[0])
    except Exception as e:
        logging.exception("GET /english_system/tab/for-exam 錯誤")
        raise HTTPException(
            status_code=500,
            detail=f"取得供測驗 English_System 失敗: {e!s}",
        )


@router.post("/tab/create")
def create_english_system_tab(body: CreateEnglishSystemRequest, caller_person_id: PersonId):
    """
    建立一筆 English_System。system_tab_id、person_id、tab_name（寫入 system_name）、local（選填，預設 false）。
    回傳 system_id、system_tab_id、tab_name（同 system_name）、person_id、local、created_at（對齊 POST /rag/tab/create）。
    """
    fid = (body.system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(status_code=400, detail="無效的 system_tab_id")
    pid = (body.person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    if pid != caller_person_id:
        raise HTTPException(status_code=400, detail="body 的 person_id 與 query 不一致")
    tab_name = (body.tab_name or "").strip()
    if not tab_name:
        raise HTTPException(status_code=400, detail="請傳入 tab_name")
    try:
        supabase = get_supabase()
        r = (
            supabase.table("English_System")
            .insert(
                _english_system_default_row(
                    fid,
                    system_name=tab_name,
                    person_id=pid,
                    local=body.local,
                )
            )
            .execute()
        )
        if not r.data or len(r.data) == 0:
            raise HTTPException(status_code=500, detail="新增 English_System 失敗")
        row = r.data[0]
        return {
            "system_id": row["system_id"],
            "system_tab_id": row["system_tab_id"],
            "tab_name": row.get("system_name"),
            "person_id": row.get("person_id"),
            "local": row.get("local"),
            "created_at": to_taipei_iso(row.get("created_at")),
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.put("/tab/tab-name", summary="Update Unit Tab Name")
def update_english_system_unit_tab_name(
    body: UpdateEnglishSystemUnitNameRequest, caller_person_id: PersonId
):
    """
    更新既有 English_System 的 system_name。以 system_id 比對；僅更新 deleted=false。
    回傳 system_id、system_tab_id、person_id、tab_name、updated_at（對齊 PUT /rag/tab/tab-name）。
    """
    if body.system_id <= 0:
        raise HTTPException(status_code=400, detail="無效的 system_id")
    tab_name = (body.tab_name or "").strip()
    if not tab_name:
        raise HTTPException(status_code=400, detail="請傳入 tab_name")
    try:
        supabase = get_supabase()
        sel = (
            supabase.table("English_System")
            .select("system_id, system_tab_id, person_id")
            .eq("system_id", body.system_id)
            .eq("deleted", False)
            .limit(1)
            .execute()
        )
        if not sel.data or len(sel.data) == 0:
            raise HTTPException(
                status_code=404,
                detail="找不到該 system_id 的 English_System 資料，或已刪除",
            )
        row = sel.data[0]
        fid = row.get("system_tab_id")
        pid = row.get("person_id")
        if ((pid or "").strip() != caller_person_id):
            raise HTTPException(status_code=403, detail="無權修改該 English_System")
        ts = now_taipei_iso()
        supabase.table("English_System").update({
            "system_name": tab_name,
            "updated_at": ts,
        }).eq("system_id", body.system_id).eq("deleted", False).execute()
        return {
            "system_id": body.system_id,
            "system_tab_id": fid,
            "person_id": pid,
            "tab_name": tab_name,
            "updated_at": ts,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/transcript/audio", response_model=TranscriptAudioResponse)
async def english_system_transcript_audio(
    request: Request,
    caller_person_id: PersonId,
    file: UploadFile = File(..., description="MP3 或其他 Deepgram 支援之常見音訊檔"),
    system_tab_id: str = Form(
        ...,
        description="English_System.system_tab_id；若尚無列則自動建立。person_id 與 query 一致",
    ),
):
    """
    上傳音檔後，先寫入 SUPABASE_ENGLISH_BUCKET（預設 english_system，路徑與 rag upload 相同），
    再以 **Deepgram** 預錄 API 轉成逐字稿（需 DEEPGRAM_API_KEY 或 System_Setting deepgram_api_key；可選 DEEPGRAM_MODEL，預設 nova-2）。
    不必先呼叫 tab/create；無對應列時會以 system_tab_id、上傳檔主檔名作 system_name 自動建立。
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="請上傳檔案並帶檔名")
    suffix = ""
    if "." in file.filename:
        suffix = "." + file.filename.rsplit(".", 1)[-1].lower()
    if suffix not in _AUDIO_SUFFIX_OK:
        raise HTTPException(
            status_code=400,
            detail=f"不支援的副檔名 {suffix!s}；請使用常見音訊格式（如 .mp3、.wav、.m4a）",
        )
    try:
        contents = await file.read()
    except Exception:
        raise HTTPException(status_code=400, detail="無法讀取上傳檔案")
    if not contents:
        raise HTTPException(status_code=400, detail="上傳檔案為空")

    fid = (system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(
            status_code=400,
            detail="請於 Form 傳入有效的 system_tab_id（不可含路徑字元）",
        )

    supabase = get_supabase()
    sel = (
        supabase.table("English_System")
        .select("system_id, person_id, file_metadata")
        .eq("system_tab_id", fid)
        .eq("deleted", False)
        .limit(1)
        .execute()
    )
    if not sel.data or len(sel.data) == 0:
        display_name = (Path(file.filename or "").stem or "").strip() or fid
        try:
            ins = (
                supabase.table("English_System")
                .insert(
                    _english_system_default_row(
                        fid,
                        system_name=display_name,
                        person_id=caller_person_id,
                        local=is_localhost_request(request),
                    )
                )
                .execute()
            )
        except Exception:
            logging.exception("自動建立 English_System（transcript/audio）")
            ins = None
        if ins and ins.data and len(ins.data) > 0:
            row = ins.data[0]
        else:
            sel2 = (
                supabase.table("English_System")
                .select("system_id, person_id, file_metadata")
                .eq("system_tab_id", fid)
                .eq("deleted", False)
                .limit(1)
                .execute()
            )
            if not sel2.data or len(sel2.data) == 0:
                raise HTTPException(
                    status_code=500,
                    detail="無法建立或讀取 English_System，請稍後再試或先呼叫 POST /english_system/tab/create",
                )
            row = sel2.data[0]
    else:
        row = sel.data[0]
    pid_row = (row.get("person_id") or "").strip()
    if pid_row != caller_person_id:
        raise HTTPException(status_code=403, detail="無權寫入該 English_System 之儲存空間")

    try:
        saved = save_english_system_upload_audio(
            contents,
            person_id=caller_person_id,
            system_tab_id=fid,
            original_filename=file.filename,
            suffix=suffix or ".mp3",
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        logging.exception("寫入 English System Storage bucket 失敗")
        raise HTTPException(status_code=500, detail=f"寫入 Storage 失敗: {e!s}") from e
    bucket_name = saved["bucket"]
    storage_path_out = saved["storage_path"]
    file_size_mb = round(len(contents) / (1024 * 1024), 6)
    prev_meta = row.get("file_metadata")
    audio_meta = {
        "system_id": row.get("system_id"),
        "system_tab_id": fid,
        "filename": saved["display_filename"],
        "bucket": bucket_name,
        "storage_path": storage_path_out,
        "stored_filename": saved["stored_filename"],
        "file_size_mb": file_size_mb,
        "kind": "english_audio",
    }
    if isinstance(prev_meta, dict):
        merged = {**prev_meta, **audio_meta}
    else:
        merged = audio_meta
    ts = now_taipei_iso()
    supabase.table("English_System").update({
        "file_metadata": to_json_safe(merged),
        "quiz_mp3_filename": saved["stored_filename"],
        "updated_at": ts,
    }).eq("system_id", row["system_id"]).eq("deleted", False).execute()

    dg_model = (os.environ.get("DEEPGRAM_MODEL") or "nova-2").strip()
    try:
        text, elapsed = transcribe_audio_bytes_deepgram(
            contents,
            suffix=suffix or ".mp3",
            model=dg_model,
        )
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e)) from e
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        logging.exception("POST /english_system/transcript/audio Deepgram 錯誤")
        raise HTTPException(status_code=500, detail=f"轉錄失敗: {e!s}") from e

    ts2 = now_taipei_iso()
    supabase.table("English_System").update({
        "quiz_text": text,
        "updated_at": ts2,
    }).eq("system_id", row["system_id"]).eq("deleted", False).execute()

    return TranscriptAudioResponse(
        text=text,
        elapsed_seconds=round(elapsed, 3),
        model=dg_model,
        filename=file.filename,
        bucket=bucket_name,
        storage_path=storage_path_out,
    )


@router.get("/transcript/youtube", response_model=TranscriptYoutubeResponse)
def english_system_transcript_youtube(
    _person_id: PersonId,
    video_id: str = Query(
        ...,
        description="YouTube video_id（11 字元）或完整影片網址",
    ),
    languages: str | None = Query(
        None,
        description="字幕語言優先序，逗號分隔（如 en,zh-TW）；未傳則等同 en",
    ),
):
    """
    擷取 YouTube 公開字幕並合併為單一純文字（不依賴 Whisper；與 Colab youtube-transcript-api 範例行為一致）。
    """
    vid = parse_youtube_video_id(video_id)
    if not vid:
        raise HTTPException(status_code=400, detail="無效的 video_id 或 YouTube 網址")
    langs: list[str] | None = None
    if languages and languages.strip():
        langs = [x.strip() for x in languages.split(",") if x.strip()]
    try:
        text, elapsed = youtube_transcript_plain_text(vid, languages=langs)
        return TranscriptYoutubeResponse(
            text=text,
            elapsed_seconds=round(elapsed, 3),
            video_id=vid,
        )
    except InvalidVideoId as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except (VideoUnavailable, NoTranscriptFound, TranscriptsDisabled) as e:
        raise HTTPException(status_code=404, detail=str(e)) from e
    except YouTubeTranscriptApiException as e:
        raise HTTPException(status_code=502, detail=str(e)) from e
    except Exception as e:
        logging.exception("GET /english_system/transcript/youtube 錯誤")
        raise HTTPException(status_code=500, detail=f"擷取字幕失敗: {e!s}") from e
