"""
English System API。對應 public."English_System" 表（測試文章；欄位與 DDL 一致）：
  system_id（bigint generated by default as identity PK）、system_tab_id、system_name、person_id、
  quiz_type（smallint NOT NULL 預設 0）、quiz_text、quiz_mp3_filename、quiz_youtube_url、
  system_metadata（json；`tab/build-system` 寫入測驗四欄快照；`transcript/audio` 寫入 `english_audio`）、
  local、deleted、updated_at、created_at。
  表啟用 RLS（Row Level Security）；後端以 service_role 寫入時不受 RLS 限制。

- GET /english_system/tabs：僅 deleted=false；person_id 與 query 相同；local 篩選（未傳則依連線是否本機）；依 created_at 舊→新（對齊 GET /rag/tabs）。
- PUT /english_system/tab/tab-name：對齊 PUT /rag/tab/tab-name（system_id、tab_name→system_name）；僅 deleted=false。
- POST /english_system/transcript/audio：上傳 MP3／音訊（Form 必填 system_tab_id）；若尚無該 system_tab_id 之 English_System 列則自動建立一筆（system_name 預設為上傳檔之主檔名，local 依連線判定）。先寫入 Supabase Storage（SUPABASE_ENGLISH_BUCKET，預設 english_system）路徑對齊 RAG：{person_id}/{system_tab_id}/upload/…，再以 **Deepgram** 預錄 API 轉逐字稿（API Key：環境變數 DEEPGRAM_API_KEY 或 System_Setting key=deepgram_api_key；可選 DEEPGRAM_MODEL 預設 nova-2），並更新 English_System.system_metadata（`english_audio`）、quiz_mp3_filename、quiz_text。
- GET /english_system/transcript/youtube：以 video_id 或 YouTube 網址擷取字幕為純文字（query：languages 逗號分隔，預設 en）。
- POST /english_system/tab/create：對齊 POST /rag/tab/create（system_tab_id、tab_name→system_name、person_id、local）。
- POST /english_system/tab/build-system：對齊 POST /rag/tab/build-rag-zip「建置完成寫表」概念（JSON body）；依 system_tab_id + person_id 更新四個測驗欄位，並將同一份資料合併寫入 **system_metadata**（與既有 JSON 合併，鍵名同欄位）。
- POST /english_system/tab/phase/create：在 build-system 之後、依 `English_System` 主鍵與 person_id 建立一筆 `English_System_Phase`（表須已依 DDL 建立並啟用 RLS；後端以 service_role 寫入）。
"""

import logging
import os
from pathlib import Path
from typing import Any

from fastapi import APIRouter, File, Form, HTTPException, Query, Request, UploadFile

from dependencies.person_id import PersonId
from pydantic import BaseModel, Field
from youtube_transcript_api._errors import (
    InvalidVideoId,
    NoTranscriptFound,
    TranscriptsDisabled,
    VideoUnavailable,
    YouTubeTranscriptApiException,
)

from utils.datetime_utils import now_taipei_iso, to_taipei_iso
from utils.english_system_storage import save_english_system_upload_audio
from utils.english_system_transcript import (
    parse_youtube_video_id,
    transcribe_audio_bytes_deepgram,
    youtube_transcript_plain_text,
)
from utils.json_utils import to_json_safe
from utils.rag_exam_setting import is_localhost_request
from utils.supabase_client import get_supabase

router = APIRouter(prefix="/english_system", tags=["english system"])


def _english_system_table_select(
    *,
    exclude_deleted: bool = True,
    local_match: bool | None = None,
) -> list[dict[str, Any]]:
    """查詢 English_System。exclude_deleted 時僅 deleted=false。local_match 指定時僅回傳該 local。依 created_at 升序。"""
    supabase = get_supabase()
    q = supabase.table("English_System").select("*")
    if exclude_deleted:
        q = q.eq("deleted", False)
    if local_match is not None:
        q = q.eq("local", local_match)
    q = q.order("created_at", desc=False)
    resp = q.execute()
    return resp.data or []


class ListEnglishSystemResponse(BaseModel):
    """GET /english_system/tabs。"""

    english_systems: list[dict] = Field(..., description="English_System 表列")
    count: int


class CreateEnglishSystemRequest(BaseModel):
    """POST /english_system/tab/create：對齊 Rag 之 tab 識別／顯示名／person_id／local。"""

    system_tab_id: str = Field(..., description="English_System.system_tab_id（對齊 Rag.rag_tab_id）")
    tab_name: str = Field(..., description="顯示名稱，寫入 English_System.system_name（對齊 Rag.tab_name）")
    person_id: str = Field(..., description="使用者識別，寫入 English_System.person_id")
    local: bool = Field(False, description="是否為本機列，寫入 English_System.local")


class CreateEnglishSystemPhaseRequest(BaseModel):
    """POST /english_system/tab/phase/create：對應 public English_System_Phase 之可寫欄位（主鍵與時間戳由資料庫產生）。"""

    english_system_id: int = Field(
        ...,
        description="所屬 English_System.system_id（須已存在、deleted=false，且 person_id 與請求一致）",
    )
    english_system_tab_id: str = Field(
        default="",
        description="寫入 English_System_Phase.english_system_tab_id；空字串則帶入父列之 system_tab_id",
    )
    person_id: str = Field(..., description="須與父列及 query 之 person_id 相同")
    quiz_phase_name: str = Field(
        default="",
        description="English_System_Phase.quiz_phase_name",
    )
    quiz_user_prompt_instruction: str | None = Field(
        None,
        description="English_System_Phase.quiz_user_prompt_instruction",
    )
    critique_user_prompt_instruction: str | None = Field(
        None,
        description="English_System_Phase.critique_user_prompt_instruction",
    )
    quiz_metadata: dict[str, Any] | None = Field(
        None,
        description="English_System_Phase.quiz_metadata（json）",
    )


class TranscriptAudioResponse(BaseModel):
    """POST /english_system/transcript/audio 回傳。"""

    text: str = Field(..., description="Deepgram 轉錄全文")
    elapsed_seconds: float = Field(..., description="自開始呼叫 Deepgram 至完成之秒數")
    model: str = Field(..., description="Deepgram model（環境變數 DEEPGRAM_MODEL，預設 nova-2）")
    filename: str | None = Field(None, description="原始上傳檔名")
    bucket: str = Field(..., description="Supabase Storage bucket 名稱")
    storage_path: str = Field(..., description="Storage 物件路徑")


class TranscriptYoutubeResponse(BaseModel):
    """GET /english_system/transcript/youtube 回傳。"""

    text: str = Field(..., description="字幕合併後之全文")
    elapsed_seconds: float = Field(..., description="擷取耗時（秒）")
    video_id: str = Field(..., description="解析後之 YouTube video_id")


_AUDIO_SUFFIX_OK = frozenset({
    ".mp3", ".wav", ".m4a", ".webm", ".ogg", ".flac", ".opus", ".mp4", ".mpeg", ".mpga", ".aac", ".wma",
})


class EnglishSystemTabBuildSystemRequest(BaseModel):
    """POST /english_system/tab/build-system：寫入 English_System 測驗欄位（語意對齊 POST /rag/tab/build-rag-zip 之 body + 更新資料表）。"""

    system_tab_id: str = Field(..., description="English_System.system_tab_id（對齊 tab/create）")
    person_id: str = Field(..., description="與該列 person_id 一致；須與 query person_id 相同")
    quiz_type: int = Field(
        0,
        ge=0,
        le=32767,
        description="English_System.quiz_type（smallint），未傳時預設 0",
    )
    quiz_text: str | None = Field(None, description="English_System.quiz_text；null 表示寫入資料庫 NULL")
    quiz_mp3_filename: str | None = Field(
        None,
        description="English_System.quiz_mp3_filename（varchar 255）",
    )
    quiz_youtube_url: str | None = Field(
        None,
        description="English_System.quiz_youtube_url（varchar 255，可存 video_id 或網址）",
    )


class EnglishSystemTabBuildSystemResponse(BaseModel):
    """POST /english_system/tab/build-system 回傳（更新後與請求一致之測驗欄位摘要）。"""

    system_id: int
    system_tab_id: str
    person_id: str | None
    quiz_type: int
    quiz_text: str | None
    quiz_mp3_filename: str | None
    quiz_youtube_url: str | None
    system_metadata: dict[str, Any] | None = Field(
        None,
        description="合併寫入後之 English_System.system_metadata（含測驗四鍵）",
    )
    updated_at: str


class UpdateEnglishSystemUnitNameRequest(BaseModel):
    """PUT /english_system/tab/tab-name：請求僅含 system_id（主鍵）、tab_name；勿傳 system_tab_id。"""

    system_id: int = Field(
        ...,
        description="English_System 主鍵，與 POST /english_system/tab/create 回傳之 system_id 相同",
    )
    tab_name: str = Field(
        ...,
        description="新的顯示名稱，寫入 English_System.system_name（對齊 Rag.tab_name）",
    )


def _english_system_default_row(
    system_tab_id: str,
    *,
    system_name: str = "",
    person_id: str = "",
    local: bool = False,
) -> dict[str, Any]:
    """English_System 新增一筆（不含 system_id，由 identity 產生）。"""
    ts = now_taipei_iso()
    return {
        "system_tab_id": system_tab_id,
        "system_name": system_name if system_name is not None else "",
        "person_id": person_id if person_id is not None else "",
        "quiz_type": 0,
        "quiz_text": None,
        "quiz_mp3_filename": None,
        "quiz_youtube_url": None,
        "system_metadata": None,
        "local": local,
        "deleted": False,
        "created_at": ts,
        "updated_at": ts,
    }


def _english_system_phase_row(
    *,
    english_system_id: int,
    english_system_tab_id: str,
    person_id: str,
    quiz_phase_name: str = "",
    quiz_user_prompt_instruction: str | None = None,
    critique_user_prompt_instruction: str | None = None,
    quiz_metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """English_System_Phase 新增一筆（不含 english_system_quiz_phase_id，由 identity 產生）。"""
    ts = now_taipei_iso()
    meta = None
    if quiz_metadata is not None:
        meta = to_json_safe(quiz_metadata)
    return {
        "english_system_id": english_system_id,
        "english_system_tab_id": english_system_tab_id if english_system_tab_id is not None else "",
        "person_id": person_id if person_id is not None else "",
        "quiz_phase_name": quiz_phase_name if quiz_phase_name is not None else "",
        "quiz_user_prompt_instruction": quiz_user_prompt_instruction,
        "critique_user_prompt_instruction": critique_user_prompt_instruction,
        "quiz_metadata": meta,
        "created_at": ts,
        "updated_at": ts,
    }


@router.get("/tabs", response_model=ListEnglishSystemResponse)
def list_english_system_tabs(
    request: Request,
    person_id: PersonId,
    local: bool | None = Query(
        None,
        description="僅回傳 English_System.local 與此值相同之列。未傳時依連線是否本機判定（對齊 GET /rag/tabs）",
    ),
):
    """
    列出 English_System，僅 deleted=false，且 person_id 與 query 相同；local 篩選同 GET /rag/tabs。
    回傳依 created_at 舊→新。
    """
    try:
        local_filter = local if local is not None else is_localhost_request(request)
        data = _english_system_table_select(exclude_deleted=True, local_match=local_filter)
        pid = person_id.strip()
        data = [r for r in data if (r.get("person_id") or "").strip() == pid]
        data = to_json_safe(data)
        return ListEnglishSystemResponse(english_systems=data, count=len(data))
    except Exception as e:
        logging.exception("GET /english_system/tabs 錯誤")
        raise HTTPException(status_code=500, detail=f"列出 English_System 失敗: {e!s}")


@router.put("/tab/tab-name", summary="Update Unit Tab Name")
def update_english_system_unit_tab_name(
    body: UpdateEnglishSystemUnitNameRequest, caller_person_id: PersonId
):
    """
    更新既有 English_System 的 system_name。以 system_id 比對；僅更新 deleted=false。
    回傳 system_id、system_tab_id、person_id、tab_name、updated_at（對齊 PUT /rag/tab/tab-name）。
    """
    if body.system_id <= 0:
        raise HTTPException(status_code=400, detail="無效的 system_id")
    tab_name = (body.tab_name or "").strip()
    if not tab_name:
        raise HTTPException(status_code=400, detail="請傳入 tab_name")
    try:
        supabase = get_supabase()
        sel = (
            supabase.table("English_System")
            .select("system_id, system_tab_id, person_id")
            .eq("system_id", body.system_id)
            .eq("deleted", False)
            .limit(1)
            .execute()
        )
        if not sel.data or len(sel.data) == 0:
            raise HTTPException(
                status_code=404,
                detail="找不到該 system_id 的 English_System 資料，或已刪除",
            )
        row = sel.data[0]
        fid = row.get("system_tab_id")
        pid = row.get("person_id")
        if ((pid or "").strip() != caller_person_id):
            raise HTTPException(status_code=403, detail="無權修改該 English_System")
        ts = now_taipei_iso()
        supabase.table("English_System").update({
            "system_name": tab_name,
            "updated_at": ts,
        }).eq("system_id", body.system_id).eq("deleted", False).execute()
        return {
            "system_id": body.system_id,
            "system_tab_id": fid,
            "person_id": pid,
            "tab_name": tab_name,
            "updated_at": ts,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/transcript/audio", response_model=TranscriptAudioResponse)
async def english_system_transcript_audio(
    request: Request,
    caller_person_id: PersonId,
    file: UploadFile = File(..., description="MP3 或其他 Deepgram 支援之常見音訊檔"),
    system_tab_id: str = Form(
        ...,
        description="English_System.system_tab_id；若尚無列則自動建立。person_id 與 query 一致",
    ),
):
    """
    上傳音檔後，先寫入 SUPABASE_ENGLISH_BUCKET（預設 english_system，路徑與 rag upload 相同），
    再以 **Deepgram** 預錄 API 轉成逐字稿（需 DEEPGRAM_API_KEY 或 System_Setting deepgram_api_key；可選 DEEPGRAM_MODEL，預設 nova-2）。
    不必先呼叫 tab/create；無對應列時會以 system_tab_id、上傳檔主檔名作 system_name 自動建立。
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="請上傳檔案並帶檔名")
    suffix = ""
    if "." in file.filename:
        suffix = "." + file.filename.rsplit(".", 1)[-1].lower()
    if suffix not in _AUDIO_SUFFIX_OK:
        raise HTTPException(
            status_code=400,
            detail=f"不支援的副檔名 {suffix!s}；請使用常見音訊格式（如 .mp3、.wav、.m4a）",
        )
    try:
        contents = await file.read()
    except Exception:
        raise HTTPException(status_code=400, detail="無法讀取上傳檔案")
    if not contents:
        raise HTTPException(status_code=400, detail="上傳檔案為空")

    fid = (system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(
            status_code=400,
            detail="請於 Form 傳入有效的 system_tab_id（不可含路徑字元）",
        )

    supabase = get_supabase()
    sel = (
        supabase.table("English_System")
        .select("system_id, person_id, system_metadata")
        .eq("system_tab_id", fid)
        .eq("deleted", False)
        .limit(1)
        .execute()
    )
    if not sel.data or len(sel.data) == 0:
        display_name = (Path(file.filename or "").stem or "").strip() or fid
        try:
            ins = (
                supabase.table("English_System")
                .insert(
                    _english_system_default_row(
                        fid,
                        system_name=display_name,
                        person_id=caller_person_id,
                        local=is_localhost_request(request),
                    )
                )
                .execute()
            )
        except Exception:
            logging.exception("自動建立 English_System（transcript/audio）")
            ins = None
        if ins and ins.data and len(ins.data) > 0:
            row = ins.data[0]
        else:
            sel2 = (
                supabase.table("English_System")
                .select("system_id, person_id, system_metadata")
                .eq("system_tab_id", fid)
                .eq("deleted", False)
                .limit(1)
                .execute()
            )
            if not sel2.data or len(sel2.data) == 0:
                raise HTTPException(
                    status_code=500,
                    detail="無法建立或讀取 English_System，請稍後再試或先呼叫 POST /english_system/tab/create",
                )
            row = sel2.data[0]
    else:
        row = sel.data[0]
    pid_row = (row.get("person_id") or "").strip()
    if pid_row != caller_person_id:
        raise HTTPException(status_code=403, detail="無權寫入該 English_System 之儲存空間")

    try:
        saved = save_english_system_upload_audio(
            contents,
            person_id=caller_person_id,
            system_tab_id=fid,
            original_filename=file.filename,
            suffix=suffix or ".mp3",
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        logging.exception("寫入 English System Storage bucket 失敗")
        raise HTTPException(status_code=500, detail=f"寫入 Storage 失敗: {e!s}") from e
    bucket_name = saved["bucket"]
    storage_path_out = saved["storage_path"]
    file_size_mb = round(len(contents) / (1024 * 1024), 6)
    prev_sys = row.get("system_metadata")
    audio_meta = {
        "filename": saved["display_filename"],
        "bucket": bucket_name,
        "storage_path": storage_path_out,
        "stored_filename": saved["stored_filename"],
        "file_size_mb": file_size_mb,
        "kind": "english_audio",
    }
    base = prev_sys if isinstance(prev_sys, dict) else {}
    merged_sys = {
        **base,
        "english_audio": {
            **(base.get("english_audio") if isinstance(base.get("english_audio"), dict) else {}),
            **audio_meta,
        },
    }
    ts = now_taipei_iso()
    supabase.table("English_System").update({
        "system_metadata": to_json_safe(merged_sys),
        "quiz_mp3_filename": saved["stored_filename"],
        "updated_at": ts,
    }).eq("system_id", row["system_id"]).eq("deleted", False).execute()

    dg_model = (os.environ.get("DEEPGRAM_MODEL") or "nova-2").strip()
    try:
        text, elapsed = transcribe_audio_bytes_deepgram(
            contents,
            suffix=suffix or ".mp3",
            model=dg_model,
        )
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e)) from e
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        logging.exception("POST /english_system/transcript/audio Deepgram 錯誤")
        raise HTTPException(status_code=500, detail=f"轉錄失敗: {e!s}") from e

    ts2 = now_taipei_iso()
    supabase.table("English_System").update({
        "quiz_text": text,
        "updated_at": ts2,
    }).eq("system_id", row["system_id"]).eq("deleted", False).execute()

    return TranscriptAudioResponse(
        text=text,
        elapsed_seconds=round(elapsed, 3),
        model=dg_model,
        filename=file.filename,
        bucket=bucket_name,
        storage_path=storage_path_out,
    )


@router.get("/transcript/youtube", response_model=TranscriptYoutubeResponse)
def english_system_transcript_youtube(
    _person_id: PersonId,
    video_id: str = Query(
        ...,
        description="YouTube video_id（11 字元）或完整影片網址",
    ),
    languages: str | None = Query(
        None,
        description="字幕語言優先序，逗號分隔（如 en,zh-TW）；未傳則等同 en",
    ),
):
    """
    擷取 YouTube 公開字幕並合併為單一純文字（不依賴 Whisper；與 Colab youtube-transcript-api 範例行為一致）。
    """
    vid = parse_youtube_video_id(video_id)
    if not vid:
        raise HTTPException(status_code=400, detail="無效的 video_id 或 YouTube 網址")
    langs: list[str] | None = None
    if languages and languages.strip():
        langs = [x.strip() for x in languages.split(",") if x.strip()]
    try:
        text, elapsed = youtube_transcript_plain_text(vid, languages=langs)
        return TranscriptYoutubeResponse(
            text=text,
            elapsed_seconds=round(elapsed, 3),
            video_id=vid,
        )
    except InvalidVideoId as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except (VideoUnavailable, NoTranscriptFound, TranscriptsDisabled) as e:
        raise HTTPException(status_code=404, detail=str(e)) from e
    except YouTubeTranscriptApiException as e:
        raise HTTPException(status_code=502, detail=str(e)) from e
    except Exception as e:
        logging.exception("GET /english_system/transcript/youtube 錯誤")
        raise HTTPException(status_code=500, detail=f"擷取字幕失敗: {e!s}") from e


@router.post("/tab/create")
def create_english_system_tab(body: CreateEnglishSystemRequest, caller_person_id: PersonId):
    """
    建立一筆 English_System。system_tab_id、person_id、tab_name（寫入 system_name）、local（選填，預設 false）。
    回傳 system_id、system_tab_id、tab_name（同 system_name）、person_id、local、created_at（對齊 POST /rag/tab/create）。
    """
    fid = (body.system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(status_code=400, detail="無效的 system_tab_id")
    pid = (body.person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    if pid != caller_person_id:
        raise HTTPException(status_code=400, detail="body 的 person_id 與 query 不一致")
    tab_name = (body.tab_name or "").strip()
    if not tab_name:
        raise HTTPException(status_code=400, detail="請傳入 tab_name")
    try:
        supabase = get_supabase()
        r = (
            supabase.table("English_System")
            .insert(
                _english_system_default_row(
                    fid,
                    system_name=tab_name,
                    person_id=pid,
                    local=body.local,
                )
            )
            .execute()
        )
        if not r.data or len(r.data) == 0:
            raise HTTPException(status_code=500, detail="新增 English_System 失敗")
        row = r.data[0]
        return {
            "system_id": row["system_id"],
            "system_tab_id": row["system_tab_id"],
            "tab_name": row.get("system_name"),
            "person_id": row.get("person_id"),
            "local": row.get("local"),
            "created_at": to_taipei_iso(row.get("created_at")),
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


_VARCHAR255_MAX = 255


@router.post(
    "/tab/build-system",
    response_model=EnglishSystemTabBuildSystemResponse,
    summary="Build English System",
)
def english_system_tab_build_system(body: EnglishSystemTabBuildSystemRequest, caller_person_id: PersonId):
    """
    依 `system_tab_id` 與 `person_id` 更新該筆 English_System（deleted=false）之 **quiz_type、quiz_text、quiz_mp3_filename、quiz_youtube_url**，
    並將此四欄之值以相同鍵名合併寫入 **system_metadata**（保留既有 JSON 其他鍵，例如 `transcript/audio` 寫入之 `english_audio`）。
    `quiz_type` 未於 body 傳入時預設為 **0**（與資料表預設一致）。
    須已存在對應列（例如已呼叫 `POST /english_system/tab/create` 或 `POST /english_system/transcript/audio` 自動建列）。
    請求格式為 JSON body，對齊 `POST /rag/tab/build-rag-zip` 之「以 body 識別 tab 並寫回資料表」用法（本端點不建 RAG、不串流 NDJSON）。
    """
    fid = (body.system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(status_code=400, detail="無效的 system_tab_id")
    pid = (body.person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    if pid != caller_person_id:
        raise HTTPException(status_code=400, detail="body 的 person_id 與 query 不一致")

    mp3 = body.quiz_mp3_filename
    if mp3 is not None and len(mp3) > _VARCHAR255_MAX:
        raise HTTPException(
            status_code=400,
            detail=f"quiz_mp3_filename 長度不可超過 {_VARCHAR255_MAX}",
        )
    yt = body.quiz_youtube_url
    if yt is not None and len(yt) > _VARCHAR255_MAX:
        raise HTTPException(
            status_code=400,
            detail=f"quiz_youtube_url 長度不可超過 {_VARCHAR255_MAX}",
        )

    ts = now_taipei_iso()
    quiz_meta = {
        "quiz_type": body.quiz_type,
        "quiz_text": body.quiz_text,
        "quiz_mp3_filename": mp3,
        "quiz_youtube_url": yt,
    }

    try:
        supabase = get_supabase()
        sel = (
            supabase.table("English_System")
            .select("system_id, system_tab_id, person_id, system_metadata")
            .eq("system_tab_id", fid)
            .eq("person_id", pid)
            .eq("deleted", False)
            .limit(1)
            .execute()
        )
        if not sel.data or len(sel.data) == 0:
            raise HTTPException(
                status_code=404,
                detail="找不到該 system_tab_id 與 person_id 之 English_System，請先呼叫 POST /english_system/tab/create",
            )
        row0 = sel.data[0]
        sid = row0["system_id"]
        prev_sys = row0.get("system_metadata")
        base_meta = prev_sys if isinstance(prev_sys, dict) else {}
        merged_meta = {**base_meta, **quiz_meta}
        update_payload: dict[str, Any] = {
            **quiz_meta,
            "system_metadata": to_json_safe(merged_meta),
            "updated_at": ts,
        }
        supabase.table("English_System").update(update_payload).eq("system_id", sid).eq("deleted", False).execute()
        meta_out = to_json_safe(merged_meta)
        return EnglishSystemTabBuildSystemResponse(
            system_id=sid,
            system_tab_id=fid,
            person_id=pid,
            quiz_type=body.quiz_type,
            quiz_text=body.quiz_text,
            quiz_mp3_filename=mp3,
            quiz_youtube_url=yt,
            system_metadata=meta_out if isinstance(meta_out, dict) else None,
            updated_at=ts,
        )
    except HTTPException:
        raise
    except Exception as e:
        logging.exception("POST /english_system/tab/build-system 錯誤")
        raise HTTPException(status_code=500, detail=str(e)) from e


@router.post(
    "/tab/phase/create",
    summary="Create English System Tab Phase",
)
def create_english_system_tab_phase(body: CreateEnglishSystemPhaseRequest, caller_person_id: PersonId):
    """
    建立一筆 English_System_Phase，須已存在 `english_system_id` 對應之 English_System（deleted=false）且 person_id 與查詢一致。
    建議先呼叫 `POST /english_system/tab/build-system` 完成測驗欄位後，再以回傳之 `system_id` 作為本請求之 `english_system_id`。
    `english_system_tab_id` 未傳或為空時，帶入父列之 `system_tab_id`；若有傳入則須與父列之 `system_tab_id` 相同。
    回傳 english_system_quiz_phase_id 與寫入欄位摘要及 created_at（對齊 tab/create 之「寫一筆子列」概念）。
    """
    if body.english_system_id <= 0:
        raise HTTPException(status_code=400, detail="無效的 english_system_id")
    pid = (body.person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    if pid != caller_person_id:
        raise HTTPException(status_code=400, detail="body 的 person_id 與 query 不一致")
    tab_id_req = (body.english_system_tab_id or "").strip()
    try:
        supabase = get_supabase()
        sel = (
            supabase.table("English_System")
            .select("system_id, system_tab_id, person_id")
            .eq("system_id", body.english_system_id)
            .eq("deleted", False)
            .limit(1)
            .execute()
        )
        if not sel.data or len(sel.data) == 0:
            raise HTTPException(
                status_code=404,
                detail="找不到該 english_system_id 的 English_System 資料，或已刪除",
            )
        parent = sel.data[0]
        p_pid = (parent.get("person_id") or "").strip()
        if p_pid != pid:
            raise HTTPException(status_code=403, detail="無權在該 English_System 下建立 Phase")
        parent_tab = (parent.get("system_tab_id") or "").strip()
        if tab_id_req:
            if tab_id_req != parent_tab:
                raise HTTPException(
                    status_code=400,
                    detail="english_system_tab_id 須與所屬 English_System.system_tab_id 相同",
                )
            eff_tab = tab_id_req
        else:
            eff_tab = parent_tab
        r = (
            supabase.table("English_System_Phase")
            .insert(
                _english_system_phase_row(
                    english_system_id=body.english_system_id,
                    english_system_tab_id=eff_tab,
                    person_id=pid,
                    quiz_phase_name=body.quiz_phase_name,
                    quiz_user_prompt_instruction=body.quiz_user_prompt_instruction,
                    critique_user_prompt_instruction=body.critique_user_prompt_instruction,
                    quiz_metadata=body.quiz_metadata,
                )
            )
            .execute()
        )
        if not r.data or len(r.data) == 0:
            raise HTTPException(status_code=500, detail="新增 English_System_Phase 失敗")
        row = r.data[0]
        return {
            "english_system_quiz_phase_id": row["english_system_quiz_phase_id"],
            "english_system_id": row["english_system_id"],
            "english_system_tab_id": row.get("english_system_tab_id"),
            "person_id": row.get("person_id"),
            "quiz_phase_name": row.get("quiz_phase_name"),
            "created_at": to_taipei_iso(row.get("created_at")),
        }
    except HTTPException:
        raise
    except Exception as e:
        logging.exception("POST /english_system/tab/phase/create 錯誤")
        raise HTTPException(status_code=500, detail=str(e)) from e
