"""
English System API。對應 public."English_System" 表（測試文章；欄位與 DDL 一致）：
  system_id（bigint generated by default as identity PK）、system_tab_id、system_name、person_id、
  quiz_type（smallint NOT NULL 預設 0）、quiz_text、quiz_mp3_filename、quiz_youtube_url、
  system_metadata（json；`tab/build-system` 寫入測驗四欄快照；`transcript/audio` 寫入 `english_audio`）、
  local、deleted、updated_at、created_at。
  表啟用 RLS（Row Level Security）；後端以 service_role 寫入時不受 RLS 限制。

- GET /english_system/tabs：僅 deleted=false；person_id 與 query 相同；local 篩選（未傳則依連線是否本機）；依 created_at 舊→新（對齊 GET /rag/tabs 與 GET /exam/tabs）。每筆帶關聯的 `English_System_Phase`（`phases`，每段含其下 `English_System_Quiz` 於 `quizzes`）、`English_System_Quiz` 每題帶一筆 `English_System_Answer` 於 `answers`；同表頂層 `answers` 為該單元全部作答列（下載／同步時一併讀入關聯，無須另呼叫已移除之舊路徑）。
- PUT /english_system/tab/tab-name：對齊 PUT /rag/tab/tab-name（system_id、tab_name→system_name）；僅 deleted=false。
- POST /english_system/transcript/audio：上傳 MP3／音訊（Form 必填 system_tab_id）；若尚無該 system_tab_id 之 English_System 列則自動建立一筆（system_name 預設為上傳檔之主檔名，local 依連線判定）。先寫入 Supabase Storage（SUPABASE_ENGLISH_BUCKET，預設 english_system）路徑對齊 RAG：{person_id}/{system_tab_id}/upload/…，再以 **Deepgram** 預錄 API 轉逐字稿（API Key：環境變數 DEEPGRAM_API_KEY 或 System_Setting key=deepgram_api_key；可選 DEEPGRAM_MODEL 預設 nova-2），並更新 English_System.system_metadata（`english_audio`）、quiz_mp3_filename、quiz_text。
- GET /english_system/transcript/youtube：以 video_id 或 YouTube 網址擷取字幕為純文字（query：languages 逗號分隔，預設 en）。
- POST /english_system/tab/create：對齊 POST /rag/tab/create（system_tab_id、tab_name→system_name、person_id、local）。
- POST /english_system/tab/build-system：對齊 POST /rag/tab/build-rag-zip「建置完成寫表」概念（JSON body）；依 system_tab_id + person_id 更新四個測驗欄位，並將同一份資料合併寫入 **system_metadata**（與既有 JSON 合併，鍵名同欄位）。
- POST /english_system/tab/phase/create：與 `utils/quiz_generation.generate_quiz` 相同模型（**gpt-4o**）；Chat **system** = **`content_text`**（教材／原文；未傳時相容 **`quiz_text`**）、**user** = **`quiz_user_prompt_instruction`**（空則預設一句）；LLM 回傳 JSON **`quiz_content`**、`quiz_answer_reference` **二者皆須非空**。成功後寫入 Phase 與 **English_System_Quiz**；HTTP 回應僅 `system_quiz_id`、`quiz_content`、`quiz_answer_reference`。
- POST /english_system/tab/phase/quiz/create：無 LLM；若寫入 Quiz 列則 **`quiz_content`／`quiz_answer_reference`／`quiz_user_prompt_instruction` 依 DDL**（寫入 Quiz 時 **`quiz_answer_reference` 必填非空**）。
- POST /english_system/tab/phase/quiz/grade：**同步** LLM 批改（無 RAG ZIP；Chat **system** = **`quiz_text`**，**user** = **`critique_user_prompt_instruction`** 並附題目／作答與與 POST `/rag/tab/quiz/grade` 相同之 JSON 輸出規格）；請求鍵名為 **`english_system_id`、`english_system_tab_id`、`english_system_quiz_phase_id`、`english_system_quiz_id`**（相容別名 **`system_*`**）；HTTP 200 直接回傳 `quiz_grade`、`quiz_comments`、`english_system_answer_id`（寫入 english_system_answer）。
"""

import json
import logging
import os
from pathlib import Path
from typing import Any

from fastapi import APIRouter, File, Form, HTTPException, Query, Request, UploadFile
from openai import OpenAI

from dependencies.person_id import PersonId
from pydantic import AliasChoices, BaseModel, Field, field_validator

from routers.grade import (
    _answer_row_payload,
    _insert_answer_table_row,
    _normalize_grading_llm_json,
    _quiz_comments_from_llm_json,
    _quiz_grade_from_llm_json,
)
from youtube_transcript_api._errors import (
    InvalidVideoId,
    NoTranscriptFound,
    TranscriptsDisabled,
    VideoUnavailable,
    YouTubeTranscriptApiException,
)

from utils.course_name_utils import get_course_name_for_prompt
from utils.datetime_utils import now_taipei_iso, to_taipei_iso
from utils.english_system_storage import save_english_system_upload_audio
from utils.english_system_transcript import (
    parse_youtube_video_id,
    transcribe_audio_bytes_deepgram,
    youtube_transcript_plain_text,
)
from utils.json_utils import to_json_safe
from utils.llm_api_key_utils import get_llm_api_key_for_person
from utils.rag_exam_setting import is_localhost_request
from utils.supabase_client import get_supabase

router = APIRouter(prefix="/english_system", tags=["english system"])

_logger_grade = logging.getLogger(__name__)


def _english_system_table_select(
    *,
    exclude_deleted: bool = True,
    local_match: bool | None = None,
) -> list[dict[str, Any]]:
    """查詢 English_System。exclude_deleted 時僅 deleted=false。local_match 指定時僅回傳該 local。依 created_at 升序。"""
    supabase = get_supabase()
    q = supabase.table("English_System").select("*")
    if exclude_deleted:
        q = q.eq("deleted", False)
    if local_match is not None:
        q = q.eq("local", local_match)
    q = q.order("created_at", desc=False)
    resp = q.execute()
    return resp.data or []


def _phases_by_english_system_id(system_ids: list[int]) -> dict[int, list[dict[str, Any]]]:
    if not system_ids:
        return {}
    supabase = get_supabase()
    resp = (
        supabase.table("English_System_Phase")
        .select("*")
        .in_("english_system_id", system_ids)
        .order("created_at", desc=False)
        .execute()
    )
    rows = resp.data or []
    out: dict[int, list[dict[str, Any]]] = {sid: [] for sid in system_ids}
    for row in rows:
        sid = row.get("english_system_id")
        if sid is not None:
            try:
                out.setdefault(int(sid), []).append(row)
            except (TypeError, ValueError):
                pass
    return out


def _quizzes_by_english_system_id(system_ids: list[int]) -> dict[int, list[dict[str, Any]]]:
    if not system_ids:
        return {}
    supabase = get_supabase()
    resp = (
        supabase.table("English_System_Quiz")
        .select("*")
        .in_("english_system_id", system_ids)
        .order("created_at", desc=False)
        .execute()
    )
    rows = resp.data or []
    out: dict[int, list[dict[str, Any]]] = {sid: [] for sid in system_ids}
    for row in rows:
        sid = row.get("english_system_id")
        if sid is not None:
            try:
                out.setdefault(int(sid), []).append(row)
            except (TypeError, ValueError):
                pass
    return out


def _answers_by_english_system_id(system_ids: list[int]) -> dict[int, list[dict[str, Any]]]:
    if not system_ids:
        return {}
    supabase = get_supabase()
    resp = (
        supabase.table("english_system_answer")
        .select("*")
        .in_("english_system_id", system_ids)
        .order("created_at", desc=False)
        .execute()
    )
    rows = resp.data or []
    out: dict[int, list[dict[str, Any]]] = {sid: [] for sid in system_ids}
    for row in rows:
        sid = row.get("english_system_id")
        if sid is not None:
            try:
                out.setdefault(int(sid), []).append(row)
            except (TypeError, ValueError):
                pass
    return out


def _answers_by_english_system_quiz_ids(
    quiz_ids: list[int],
) -> dict[int, list[dict[str, Any]]]:
    if not quiz_ids:
        return {}
    supabase = get_supabase()
    resp = (
        supabase.table("english_system_answer")
        .select("*")
        .in_("english_system_quiz_id", quiz_ids)
        .execute()
    )
    rows = resp.data or []
    out: dict[int, list[dict[str, Any]]] = {qid: [] for qid in quiz_ids}
    for row in rows:
        qid = row.get("english_system_quiz_id")
        if qid is not None:
            try:
                out.setdefault(int(qid), []).append(row)
            except (TypeError, ValueError):
                pass
    return out


def _enrich_english_system_rows_with_relations(data: list[dict[str, Any]]) -> None:
    """併入 English_System_Phase（phases，每段含 quizzes）、每題一筆 English_System_Answer（同 GET /rag/tabs 取第一筆），頂層 answers 為該單元全部作答。"""
    if not data:
        return
    system_ids: list[int] = []
    for row in data:
        sid = row.get("system_id")
        if sid is not None:
            try:
                system_ids.append(int(sid))
            except (TypeError, ValueError):
                pass
    system_ids = list(dict.fromkeys(system_ids))
    if not system_ids:
        return
    phases_by = _phases_by_english_system_id(system_ids)
    quizzes_by = _quizzes_by_english_system_id(system_ids)
    answers_by = _answers_by_english_system_id(system_ids)
    all_quiz_ids: list[int] = []
    for sid in system_ids:
        for q in quizzes_by.get(sid, []):
            qid = q.get("english_system_quiz_id")
            if qid is not None:
                try:
                    all_quiz_ids.append(int(qid))
                except (TypeError, ValueError):
                    pass
    all_quiz_ids = list(dict.fromkeys(all_quiz_ids))
    answers_by_qid = _answers_by_english_system_quiz_ids(all_quiz_ids)

    for row in data:
        sid = row.get("system_id")
        if sid is None:
            continue
        try:
            sid_int = int(sid)
        except (TypeError, ValueError):
            continue
        phases = phases_by.get(sid_int, [])
        all_quizzes = quizzes_by.get(sid_int, [])
        phase_id_set: set[int] = set()
        for p in phases:
            pid = p.get("english_system_quiz_phase_id")
            if pid is not None:
                try:
                    phase_id_set.add(int(pid))
                except (TypeError, ValueError):
                    pass
        by_phase: dict[int, list[dict[str, Any]]] = {}
        orphans: list[dict[str, Any]] = []
        for q in all_quizzes:
            qpid = q.get("english_system_quiz_phase_id")
            try:
                qpid_i = int(qpid) if qpid is not None else None
            except (TypeError, ValueError):
                qpid_i = None
            if qpid_i is not None and qpid_i in phase_id_set:
                by_phase.setdefault(qpid_i, []).append(q)
            else:
                orphans.append(q)
        for ph in phases:
            pid = ph.get("english_system_quiz_phase_id")
            try:
                pid_i = int(pid) if pid is not None else None
            except (TypeError, ValueError):
                pid_i = None
            p_quizzes = by_phase.get(pid_i, []) if pid_i is not None else []
            for quiz in p_quizzes:
                qid = quiz.get("english_system_quiz_id")
                try:
                    qid_i = int(qid) if qid is not None else None
                except (TypeError, ValueError):
                    qid_i = None
                raw = (answers_by_qid.get(qid_i, []) or []) if qid_i is not None else []
                quiz["answers"] = raw[:1]
            ph["quizzes"] = p_quizzes
        for quiz in orphans:
            qid = quiz.get("english_system_quiz_id")
            try:
                qid_i = int(qid) if qid is not None else None
            except (TypeError, ValueError):
                qid_i = None
            raw = (answers_by_qid.get(qid_i, []) or []) if qid_i is not None else []
            quiz["answers"] = raw[:1]
        row["phases"] = phases
        row["quizzes"] = orphans
        row["answers"] = answers_by.get(sid_int, [])


class ListEnglishSystemResponse(BaseModel):
    """GET /english_system/tabs：每筆含 phases（每段含 quizzes，每題含 answers）、與該單元頂層 answers。"""

    english_systems: list[dict] = Field(
        ...,
        description="English_System 表列，每筆帶 phases／quizzes／關聯 answers（同 GET /exam/tabs 之巢狀概念）",
    )
    count: int


class CreateEnglishSystemRequest(BaseModel):
    """POST /english_system/tab/create：對齊 Rag 之 tab 識別／顯示名／person_id／local。"""

    system_tab_id: str = Field(..., description="English_System.system_tab_id（對齊 Rag.rag_tab_id）")
    tab_name: str = Field(..., description="顯示名稱，寫入 English_System.system_name（對齊 Rag.tab_name）")
    person_id: str = Field(..., description="使用者識別，寫入 English_System.person_id")
    local: bool = Field(False, description="是否為本機列，寫入 English_System.local")


class CreateEnglishSystemPhaseRequest(BaseModel):
    """POST /english_system/tab/phase/create（LLM 出題）與 /tab/phase/quiz/create（無 LLM 草稿）共用 body。"""

    system_id: int = Field(
        ...,
        gt=0,
        description="English_System.system_id（須已存在、deleted=false，且與 query person_id 一致）",
    )
    system_tab_id: str = Field(
        ...,
        description="English_System.system_tab_id（須與該列一致）",
    )
    system_quiz_phase_id: int = Field(
        0,
        ge=0,
        description="0：新建 English_System_Phase（主鍵由資料庫產生）；>0：更新既有 Phase（該 english_system_quiz_phase_id）之 quiz_phase_name",
    )
    quiz_phase_name: str = Field(default="", description="English_System_Phase.quiz_phase_name")
    quiz_content: str = Field(
        default="",
        description="僅 POST /tab/phase/quiz/create（無 LLM）：題目草稿 → English_System_Quiz.quiz_content。不包含 LLM；若需依原文自動出題請用 POST /tab/phase/create 並傳 content_text。",
    )
    content_text: str = Field(
        default="",
        description="僅 POST /tab/phase/create（LLM）：Chat **system**，教材／原文（模型據此與 user 指令產生題目）；未傳時相容沿用 quiz_text",
    )
    quiz_text: str = Field(
        default="",
        description="相容：POST /tab/phase/create（LLM）未傳 content_text 時當 system。POST /tab/phase/quiz/create：若未傳 quiz_content，誤傳至此仍視為題目草稿。",
    )
    quiz_user_prompt_instruction: str = Field(
        default="",
        description="POST /tab/phase/create：LLM **user**。POST /tab/phase/quiz/create：寫入 English_System_Quiz.quiz_user_prompt_instruction",
    )
    quiz_answer_reference: str = Field(
        default="",
        description="POST /tab/phase/quiz/create（無 LLM）：欲寫入 Quiz 列時與 quiz_content 一併必填（參考答案／提示）。POST /tab/phase/create（LLM）：無需傳，由模型產出。",
    )
    @classmethod
    def _system_tab_id_as_str(cls, v: Any) -> str:
        if v is None:
            return ""
        return str(v).strip()


class EnglishSystemPhaseCreateLLMResponse(BaseModel):
    """POST /english_system/tab/phase/create 與 POST /english_system/tab/phase/quiz/create（無 LLM）共用之最小回傳。"""

    system_quiz_id: int = Field(..., description="English_System_Quiz 主鍵；無草稿時為 0")
    quiz_content: str = Field(..., description="題目")
    quiz_answer_reference: str = Field(
        ...,
        description="參考答案或提示；僅 Phase／無 Quiz 列時可為空字串",
    )


class EnglishSystemQuizGradeRequest(BaseModel):
    """POST /english_system/tab/phase/quiz/grade：寫入 english_system_answer（對齊 Rag_Answer／Exam_Answer 之 quiz_answer、quiz_grade、quiz_grade_metadata）。
    請求鍵名使用 **english_system_***（相容別名 **system_***）。"""

    english_system_id: int = Field(
        ...,
        gt=0,
        description="English_System.system_id",
        validation_alias=AliasChoices("english_system_id", "system_id"),
    )
    english_system_tab_id: str = Field(
        ...,
        description="English_System.system_tab_id",
        validation_alias=AliasChoices("english_system_tab_id", "system_tab_id"),
    )
    english_system_quiz_phase_id: int = Field(
        0,
        ge=0,
        description="English_System_Phase／Quiz 關聯之 english_system_quiz_phase_id；0 時僅依其它鍵寫入作答列",
        validation_alias=AliasChoices("english_system_quiz_phase_id", "system_quiz_phase_id"),
    )
    english_system_quiz_id: int = Field(
        0,
        ge=0,
        description="English_System_Quiz 主鍵 english_system_quiz_id；>0 時會驗證該題屬於此 english_system／tab／person（並與 phase 一致）",
        validation_alias=AliasChoices("english_system_quiz_id", "system_quiz_id"),
    )
    quiz_text: str = Field(
        ...,
        description="Chat **system**：教材／原文脈絡（對齊 English_System.quiz_text 概念）",
    )
    quiz_content: str = Field(..., description="測驗題目全文（批改依據之一）")
    critique_user_prompt_instruction: str = Field(
        ...,
        description="Chat **user** 之主指令（批改說明／準則）；後端會另附題目、學生答案與輸出 JSON 規格",
    )
    quiz_answer: str = Field(
        ...,
        description="學生作答（寫入 english_system_answer.quiz_answer）；相容舊欄位 answer",
        validation_alias=AliasChoices("quiz_answer", "answer"),
    )


class EnglishSystemQuizGradeResponse(BaseModel):
    """POST /english_system/tab/phase/quiz/grade：同步回傳（對齊 Rag 評分之 quiz_grade、quiz_comments）。"""

    quiz_grade: int = Field(..., description="0～5 整數")
    quiz_comments: list[str] = Field(default_factory=list, description="評語（繁體中文）")
    english_system_answer_id: int | None = Field(
        None,
        description="寫入 english_system_answer 之主鍵；寫入失敗時為 null",
    )


class TranscriptAudioResponse(BaseModel):
    """POST /english_system/transcript/audio 回傳。"""

    text: str = Field(..., description="Deepgram 轉錄全文")
    elapsed_seconds: float = Field(..., description="自開始呼叫 Deepgram 至完成之秒數")
    model: str = Field(..., description="Deepgram model（環境變數 DEEPGRAM_MODEL，預設 nova-2）")
    filename: str | None = Field(None, description="原始上傳檔名")
    bucket: str = Field(..., description="Supabase Storage bucket 名稱")
    storage_path: str = Field(..., description="Storage 物件路徑")


class TranscriptYoutubeResponse(BaseModel):
    """GET /english_system/transcript/youtube 回傳。"""

    text: str = Field(..., description="字幕合併後之全文")
    elapsed_seconds: float = Field(..., description="擷取耗時（秒）")
    video_id: str = Field(..., description="解析後之 YouTube video_id")


_AUDIO_SUFFIX_OK = frozenset({
    ".mp3", ".wav", ".m4a", ".webm", ".ogg", ".flac", ".opus", ".mp4", ".mpeg", ".mpga", ".aac", ".wma",
})


class EnglishSystemTabBuildSystemRequest(BaseModel):
    """POST /english_system/tab/build-system：寫入 English_System 測驗欄位（語意對齊 POST /rag/tab/build-rag-zip 之 body + 更新資料表）。"""

    system_tab_id: str = Field(..., description="English_System.system_tab_id（對齊 tab/create）")
    person_id: str = Field(..., description="與該列 person_id 一致；須與 query person_id 相同")
    quiz_type: int = Field(
        0,
        ge=0,
        le=32767,
        description="English_System.quiz_type（smallint），未傳時預設 0",
    )
    quiz_text: str | None = Field(None, description="English_System.quiz_text；null 表示寫入資料庫 NULL")
    quiz_mp3_filename: str | None = Field(
        None,
        description="English_System.quiz_mp3_filename（varchar 255）",
    )
    quiz_youtube_url: str | None = Field(
        None,
        description="English_System.quiz_youtube_url（varchar 255，可存 video_id 或網址）",
    )


class EnglishSystemTabBuildSystemResponse(BaseModel):
    """POST /english_system/tab/build-system 回傳（更新後與請求一致之測驗欄位摘要）。"""

    system_id: int
    system_tab_id: str
    person_id: str | None
    quiz_type: int
    quiz_text: str | None
    quiz_mp3_filename: str | None
    quiz_youtube_url: str | None
    system_metadata: dict[str, Any] | None = Field(
        None,
        description="合併寫入後之 English_System.system_metadata（含測驗四鍵）",
    )
    updated_at: str


class UpdateEnglishSystemUnitNameRequest(BaseModel):
    """PUT /english_system/tab/tab-name：請求僅含 system_id（主鍵）、tab_name；勿傳 system_tab_id。"""

    system_id: int = Field(
        ...,
        description="English_System 主鍵，與 POST /english_system/tab/create 回傳之 system_id 相同",
    )
    tab_name: str = Field(
        ...,
        description="新的顯示名稱，寫入 English_System.system_name（對齊 Rag.tab_name）",
    )


def _english_system_default_row(
    system_tab_id: str,
    *,
    system_name: str = "",
    person_id: str = "",
    local: bool = False,
) -> dict[str, Any]:
    """English_System 新增一筆（不含 system_id，由 identity 產生）。"""
    ts = now_taipei_iso()
    return {
        "system_tab_id": system_tab_id,
        "system_name": system_name if system_name is not None else "",
        "person_id": person_id if person_id is not None else "",
        "quiz_type": 0,
        "quiz_text": None,
        "quiz_mp3_filename": None,
        "quiz_youtube_url": None,
        "system_metadata": None,
        "local": local,
        "deleted": False,
        "created_at": ts,
        "updated_at": ts,
    }


def _english_system_phase_row(
    *,
    english_system_id: int,
    english_system_tab_id: str,
    person_id: str,
    quiz_phase_name: str = "",
) -> dict[str, Any]:
    """English_System_Phase 新增一筆（不含 english_system_quiz_phase_id，由 identity 產生；欄位同目前 DDL）。"""
    ts = now_taipei_iso()
    return {
        "english_system_id": english_system_id,
        "english_system_tab_id": english_system_tab_id if english_system_tab_id is not None else "",
        "person_id": person_id if person_id is not None else "",
        "quiz_phase_name": quiz_phase_name if quiz_phase_name is not None else "",
        "created_at": ts,
        "updated_at": ts,
    }


def _english_system_quiz_row_phase_create(
    *,
    english_system_id: int,
    english_system_quiz_phase_id: int,
    english_system_tab_id: str,
    person_id: str,
    quiz_user_prompt_instruction: str,
    quiz_content: str,
    quiz_answer_reference: str,
    quiz_metadata: dict[str, Any] | None,
) -> dict[str, Any]:
    """English_System_Quiz 新增一筆（不含 english_system_quiz_id；欄位同 DDL）。"""
    ts = now_taipei_iso()
    up = (quiz_user_prompt_instruction or "").strip()
    meta = to_json_safe(quiz_metadata) if quiz_metadata is not None else None
    return {
        "english_system_id": english_system_id,
        "english_system_quiz_phase_id": english_system_quiz_phase_id,
        "english_system_tab_id": english_system_tab_id if english_system_tab_id is not None else "",
        "person_id": person_id if person_id is not None else "",
        "quiz_user_prompt_instruction": up if up else None,
        "quiz_content": quiz_content if quiz_content else None,
        "quiz_answer_reference": ((quiz_answer_reference or "").strip() or None),
        "quiz_rate": "",
        "quiz_metadata": meta,
        "created_at": ts,
        "updated_at": ts,
    }


# 與 utils.quiz_generation.generate_quiz 之 chat 模型一致
_ENGLISH_TAB_PHASE_LLM_MODEL = "gpt-4o"

_PHASE_CREATE_JSON_SUFFIX = (
    "\n\n你是測驗出題助理。上方為教材／原文（system）。使用者訊息為出題指令（user）。"
    "請依教材與指令產出一道測驗題；並務必給出「參考解答」或「答題步驟／提示」（二者至少擇一寫入 quiz_answer_reference）。"
    "\n\n【回傳格式】請僅以 JSON 輸出（勿附其他文字）。"
    "**quiz_content** = 題幹與設問（不可為空）。"
    "**quiz_answer_reference** = 參考答案全文 **或** 解題提示／步驟提示（不可為空、不可僅空白）；若題型為開放題，請給評分要點或範例要點。"
    '鍵名必須為：{"quiz_content":"…","quiz_answer_reference":"…"}。請使用繁體中文。'
)


def _parse_phase_create_llm_json(raw: str) -> tuple[str, str]:
    try:
        data = json.loads(raw or "{}")
    except json.JSONDecodeError:
        return "", ""
    if not isinstance(data, dict):
        return "", ""
    qc = data.get("quiz_content")
    qar = data.get("quiz_answer_reference")
    if qar is None:
        qar = data.get("quiz_reference_answer")
    if qar is None:
        qar = data.get("reference_answer")
    if qar is None:
        qar = data.get("quiz_hint")
    if qar is None:
        qar = data.get("quiz_hints")
    if qar is None:
        qar = data.get("hint")
    if qar is None:
        qar = data.get("hints")
    return str(qc or "").strip(), str(qar or "").strip()


def _english_tab_phase_llm_generate(
    *,
    content_text: str,
    quiz_user_prompt_instruction: str,
    api_key: str,
) -> tuple[str, str]:
    sys_inner = (content_text or "").strip()
    if not sys_inner:
        raise ValueError("content_text（教材／原文）不可為空")
    system_content = sys_inner + _PHASE_CREATE_JSON_SUFFIX
    user_content = (quiz_user_prompt_instruction or "").strip() or (
        "請依上述教材原文出題：產生一道測驗題。"
        "**請務必**在 JSON 中同時給出非空的 quiz_content（題目）與 quiz_answer_reference（參考答案或答題提示）。"
    )
    client = OpenAI(api_key=api_key)

    def _call(user_msg: str) -> tuple[str, str]:
        response = client.chat.completions.create(
            model=_ENGLISH_TAB_PHASE_LLM_MODEL,
            messages=[
                {"role": "system", "content": system_content},
                {"role": "user", "content": user_msg},
            ],
            response_format={"type": "json_object"},
            temperature=0.7,
        )
        raw = response.choices[0].message.content or "{}"
        return _parse_phase_create_llm_json(raw)

    qc, qar = _call(user_content)
    if (qc or "").strip() and not (qar or "").strip():
        qc2, qar2 = _call(
            user_content
            + "\n\n【補充要求】上一輪 JSON 缺少或為空的 quiz_answer_reference。"
            "請重新輸出完整 JSON，**quiz_answer_reference** 須為非空字串："
            "請寫「參考答案」或「解題步驟／評分要點」至少一項。"
        )
        qc, qar = qc2, qar2
    return qc, qar


def _upsert_english_system_phase_row(
    supabase: Any,
    *,
    body: CreateEnglishSystemPhaseRequest,
    pid: str,
    eff_tab: str,
    qname: str,
) -> tuple[int, str]:
    phase_id: int
    phase_created_at: str
    if body.system_quiz_phase_id <= 0:
        r = (
            supabase.table("English_System_Phase")
            .insert(
                _english_system_phase_row(
                    english_system_id=body.system_id,
                    english_system_tab_id=eff_tab,
                    person_id=pid,
                    quiz_phase_name=qname,
                )
            )
            .execute()
        )
        if not r.data or len(r.data) == 0:
            raise HTTPException(status_code=500, detail="新增 English_System_Phase 失敗")
        row = r.data[0]
        phase_id = row["english_system_quiz_phase_id"]
        phase_created_at = to_taipei_iso(row.get("created_at")) or now_taipei_iso()
    else:
        phase_id = body.system_quiz_phase_id
        chk = (
            supabase.table("English_System_Phase")
            .select("english_system_quiz_phase_id, created_at")
            .eq("english_system_quiz_phase_id", phase_id)
            .eq("english_system_id", body.system_id)
            .eq("english_system_tab_id", eff_tab)
            .eq("person_id", pid)
            .limit(1)
            .execute()
        )
        if not chk.data or len(chk.data) == 0:
            raise HTTPException(
                status_code=404,
                detail="找不到符合 system_id、system_tab_id、person_id 之 English_System_Phase",
            )
        ts_u = now_taipei_iso()
        supabase.table("English_System_Phase").update({
            "quiz_phase_name": qname,
            "updated_at": ts_u,
        }).eq("english_system_quiz_phase_id", phase_id).eq("english_system_id", body.system_id).execute()
        phase_created_at = to_taipei_iso(chk.data[0].get("created_at")) or now_taipei_iso()
    return phase_id, phase_created_at


def _insert_english_system_quiz_for_phase(
    supabase: Any,
    *,
    body: CreateEnglishSystemPhaseRequest,
    pid: str,
    eff_tab: str,
    phase_id: int,
    quiz_user_prompt_instruction: str,
    quiz_content: str,
    quiz_answer_reference: str,
    quiz_metadata: dict[str, Any] | None,
) -> int:
    ins_row = _english_system_quiz_row_phase_create(
        english_system_id=body.system_id,
        english_system_quiz_phase_id=phase_id,
        english_system_tab_id=eff_tab,
        person_id=pid,
        quiz_user_prompt_instruction=quiz_user_prompt_instruction,
        quiz_content=quiz_content,
        quiz_answer_reference=quiz_answer_reference,
        quiz_metadata=quiz_metadata,
    )
    ins = supabase.table("English_System_Quiz").insert(ins_row).execute()
    if not ins.data or len(ins.data) == 0:
        raise HTTPException(status_code=500, detail="寫入 English_System_Quiz 失敗")
    return ins.data[0]["english_system_quiz_id"]


def _validate_phase_parent_context(
    supabase: Any,
    *,
    system_id: int,
    fid: str,
    pid: str,
) -> str:
    """確認 English_System 存在且 system_tab_id、person_id 與請求一致；回傳 eff_tab（= fid）。"""
    sel = (
        supabase.table("English_System")
        .select("system_id, system_tab_id, person_id")
        .eq("system_id", system_id)
        .eq("deleted", False)
        .limit(1)
        .execute()
    )
    if not sel.data or len(sel.data) == 0:
        raise HTTPException(
            status_code=404,
            detail="找不到該 system_id 的 English_System 資料，或已刪除",
        )
    parent = sel.data[0]
    p_pid = (parent.get("person_id") or "").strip()
    if p_pid != pid:
        raise HTTPException(status_code=403, detail="無權在該 English_System 下建立或更新 Phase")
    parent_tab = (parent.get("system_tab_id") or "").strip()
    if fid != parent_tab:
        raise HTTPException(
            status_code=400,
            detail="system_tab_id 須與所屬 English_System.system_tab_id 相同",
        )
    return fid


@router.get(
    "/tabs",
    response_model=ListEnglishSystemResponse,
    summary="List English System Tabs",
)
def list_english_system_tabs(
    request: Request,
    person_id: PersonId,
    local: bool | None = Query(
        None,
        description="僅回傳 English_System.local 與此值相同之列。未傳時依連線是否本機判定（對齊 GET /rag/tabs）",
    ),
):
    """
    列出 English_System，僅 deleted=false，且 person_id 與 query 相同；local 篩選同 GET /rag/tabs。
    回傳依 created_at 舊→新。每筆併入 `English_System_Phase`（`phases`，每段含其下 `English_System_Quiz` 於 `quizzes`）、
    每題至多一筆 `English_System_Answer` 於 `quizzes[].answers`；`quizzes` 若為非空則為所屬 phase 已不存在之題目；頂層 `answers` 為該單元全部作答列（下載／同步可僅用本端點，無須分開抓 Phase）。
    """
    try:
        local_filter = local if local is not None else is_localhost_request(request)
        data = _english_system_table_select(exclude_deleted=True, local_match=local_filter)
        pid = person_id.strip()
        data = [r for r in data if (r.get("person_id") or "").strip() == pid]
        _enrich_english_system_rows_with_relations(data)
        data = to_json_safe(data)
        return ListEnglishSystemResponse(english_systems=data, count=len(data))
    except Exception as e:
        logging.exception("GET /english_system/tabs 錯誤")
        raise HTTPException(status_code=500, detail=f"列出 English_System 失敗: {e!s}")


@router.put("/tab/tab-name", summary="Update Unit Tab Name")
def update_english_system_unit_tab_name(
    body: UpdateEnglishSystemUnitNameRequest, caller_person_id: PersonId
):
    """
    更新既有 English_System 的 system_name。以 system_id 比對；僅更新 deleted=false。
    回傳 system_id、system_tab_id、person_id、tab_name、updated_at（對齊 PUT /rag/tab/tab-name）。
    """
    if body.system_id <= 0:
        raise HTTPException(status_code=400, detail="無效的 system_id")
    tab_name = (body.tab_name or "").strip()
    if not tab_name:
        raise HTTPException(status_code=400, detail="請傳入 tab_name")
    try:
        supabase = get_supabase()
        sel = (
            supabase.table("English_System")
            .select("system_id, system_tab_id, person_id")
            .eq("system_id", body.system_id)
            .eq("deleted", False)
            .limit(1)
            .execute()
        )
        if not sel.data or len(sel.data) == 0:
            raise HTTPException(
                status_code=404,
                detail="找不到該 system_id 的 English_System 資料，或已刪除",
            )
        row = sel.data[0]
        fid = row.get("system_tab_id")
        pid = row.get("person_id")
        if ((pid or "").strip() != caller_person_id):
            raise HTTPException(status_code=403, detail="無權修改該 English_System")
        ts = now_taipei_iso()
        supabase.table("English_System").update({
            "system_name": tab_name,
            "updated_at": ts,
        }).eq("system_id", body.system_id).eq("deleted", False).execute()
        return {
            "system_id": body.system_id,
            "system_tab_id": fid,
            "person_id": pid,
            "tab_name": tab_name,
            "updated_at": ts,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/transcript/audio", response_model=TranscriptAudioResponse)
async def english_system_transcript_audio(
    request: Request,
    caller_person_id: PersonId,
    file: UploadFile = File(..., description="MP3 或其他 Deepgram 支援之常見音訊檔"),
    system_tab_id: str = Form(
        ...,
        description="English_System.system_tab_id；若尚無列則自動建立。person_id 與 query 一致",
    ),
):
    """
    上傳音檔後，先寫入 SUPABASE_ENGLISH_BUCKET（預設 english_system，路徑與 rag upload 相同），
    再以 **Deepgram** 預錄 API 轉成逐字稿（需 DEEPGRAM_API_KEY 或 System_Setting deepgram_api_key；可選 DEEPGRAM_MODEL，預設 nova-2）。
    不必先呼叫 tab/create；無對應列時會以 system_tab_id、上傳檔主檔名作 system_name 自動建立。
    """
    if not file.filename:
        raise HTTPException(status_code=400, detail="請上傳檔案並帶檔名")
    suffix = ""
    if "." in file.filename:
        suffix = "." + file.filename.rsplit(".", 1)[-1].lower()
    if suffix not in _AUDIO_SUFFIX_OK:
        raise HTTPException(
            status_code=400,
            detail=f"不支援的副檔名 {suffix!s}；請使用常見音訊格式（如 .mp3、.wav、.m4a）",
        )
    try:
        contents = await file.read()
    except Exception:
        raise HTTPException(status_code=400, detail="無法讀取上傳檔案")
    if not contents:
        raise HTTPException(status_code=400, detail="上傳檔案為空")

    fid = (system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(
            status_code=400,
            detail="請於 Form 傳入有效的 system_tab_id（不可含路徑字元）",
        )

    supabase = get_supabase()
    sel = (
        supabase.table("English_System")
        .select("system_id, person_id, system_metadata")
        .eq("system_tab_id", fid)
        .eq("deleted", False)
        .limit(1)
        .execute()
    )
    if not sel.data or len(sel.data) == 0:
        display_name = (Path(file.filename or "").stem or "").strip() or fid
        try:
            ins = (
                supabase.table("English_System")
                .insert(
                    _english_system_default_row(
                        fid,
                        system_name=display_name,
                        person_id=caller_person_id,
                        local=is_localhost_request(request),
                    )
                )
                .execute()
            )
        except Exception:
            logging.exception("自動建立 English_System（transcript/audio）")
            ins = None
        if ins and ins.data and len(ins.data) > 0:
            row = ins.data[0]
        else:
            sel2 = (
                supabase.table("English_System")
                .select("system_id, person_id, system_metadata")
                .eq("system_tab_id", fid)
                .eq("deleted", False)
                .limit(1)
                .execute()
            )
            if not sel2.data or len(sel2.data) == 0:
                raise HTTPException(
                    status_code=500,
                    detail="無法建立或讀取 English_System，請稍後再試或先呼叫 POST /english_system/tab/create",
                )
            row = sel2.data[0]
    else:
        row = sel.data[0]
    pid_row = (row.get("person_id") or "").strip()
    if pid_row != caller_person_id:
        raise HTTPException(status_code=403, detail="無權寫入該 English_System 之儲存空間")

    try:
        saved = save_english_system_upload_audio(
            contents,
            person_id=caller_person_id,
            system_tab_id=fid,
            original_filename=file.filename,
            suffix=suffix or ".mp3",
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        logging.exception("寫入 English System Storage bucket 失敗")
        raise HTTPException(status_code=500, detail=f"寫入 Storage 失敗: {e!s}") from e
    bucket_name = saved["bucket"]
    storage_path_out = saved["storage_path"]
    file_size_mb = round(len(contents) / (1024 * 1024), 6)
    prev_sys = row.get("system_metadata")
    audio_meta = {
        "filename": saved["display_filename"],
        "bucket": bucket_name,
        "storage_path": storage_path_out,
        "stored_filename": saved["stored_filename"],
        "file_size_mb": file_size_mb,
        "kind": "english_audio",
    }
    base = prev_sys if isinstance(prev_sys, dict) else {}
    merged_sys = {
        **base,
        "english_audio": {
            **(base.get("english_audio") if isinstance(base.get("english_audio"), dict) else {}),
            **audio_meta,
        },
    }
    ts = now_taipei_iso()
    supabase.table("English_System").update({
        "system_metadata": to_json_safe(merged_sys),
        "quiz_mp3_filename": saved["stored_filename"],
        "updated_at": ts,
    }).eq("system_id", row["system_id"]).eq("deleted", False).execute()

    dg_model = (os.environ.get("DEEPGRAM_MODEL") or "nova-2").strip()
    try:
        text, elapsed = transcribe_audio_bytes_deepgram(
            contents,
            suffix=suffix or ".mp3",
            model=dg_model,
        )
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e)) from e
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        logging.exception("POST /english_system/transcript/audio Deepgram 錯誤")
        raise HTTPException(status_code=500, detail=f"轉錄失敗: {e!s}") from e

    ts2 = now_taipei_iso()
    supabase.table("English_System").update({
        "quiz_text": text,
        "updated_at": ts2,
    }).eq("system_id", row["system_id"]).eq("deleted", False).execute()

    return TranscriptAudioResponse(
        text=text,
        elapsed_seconds=round(elapsed, 3),
        model=dg_model,
        filename=file.filename,
        bucket=bucket_name,
        storage_path=storage_path_out,
    )


@router.get("/transcript/youtube", response_model=TranscriptYoutubeResponse)
def english_system_transcript_youtube(
    _person_id: PersonId,
    video_id: str = Query(
        ...,
        description="YouTube video_id（11 字元）或完整影片網址",
    ),
    languages: str | None = Query(
        None,
        description="字幕語言優先序，逗號分隔（如 en,zh-TW）；未傳則等同 en",
    ),
):
    """
    擷取 YouTube 公開字幕並合併為單一純文字（不依賴 Whisper；與 Colab youtube-transcript-api 範例行為一致）。
    """
    vid = parse_youtube_video_id(video_id)
    if not vid:
        raise HTTPException(status_code=400, detail="無效的 video_id 或 YouTube 網址")
    langs: list[str] | None = None
    if languages and languages.strip():
        langs = [x.strip() for x in languages.split(",") if x.strip()]
    try:
        text, elapsed = youtube_transcript_plain_text(vid, languages=langs)
        return TranscriptYoutubeResponse(
            text=text,
            elapsed_seconds=round(elapsed, 3),
            video_id=vid,
        )
    except InvalidVideoId as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except (VideoUnavailable, NoTranscriptFound, TranscriptsDisabled) as e:
        raise HTTPException(status_code=404, detail=str(e)) from e
    except YouTubeTranscriptApiException as e:
        raise HTTPException(status_code=502, detail=str(e)) from e
    except Exception as e:
        logging.exception("GET /english_system/transcript/youtube 錯誤")
        raise HTTPException(status_code=500, detail=f"擷取字幕失敗: {e!s}") from e


@router.post("/tab/create")
def create_english_system_tab(body: CreateEnglishSystemRequest, caller_person_id: PersonId):
    """
    建立一筆 English_System。system_tab_id、person_id、tab_name（寫入 system_name）、local（選填，預設 false）。
    回傳 system_id、system_tab_id、tab_name（同 system_name）、person_id、local、created_at（對齊 POST /rag/tab/create）。
    """
    fid = (body.system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(status_code=400, detail="無效的 system_tab_id")
    pid = (body.person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    if pid != caller_person_id:
        raise HTTPException(status_code=400, detail="body 的 person_id 與 query 不一致")
    tab_name = (body.tab_name or "").strip()
    if not tab_name:
        raise HTTPException(status_code=400, detail="請傳入 tab_name")
    try:
        supabase = get_supabase()
        r = (
            supabase.table("English_System")
            .insert(
                _english_system_default_row(
                    fid,
                    system_name=tab_name,
                    person_id=pid,
                    local=body.local,
                )
            )
            .execute()
        )
        if not r.data or len(r.data) == 0:
            raise HTTPException(status_code=500, detail="新增 English_System 失敗")
        row = r.data[0]
        return {
            "system_id": row["system_id"],
            "system_tab_id": row["system_tab_id"],
            "tab_name": row.get("system_name"),
            "person_id": row.get("person_id"),
            "local": row.get("local"),
            "created_at": to_taipei_iso(row.get("created_at")),
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


_VARCHAR255_MAX = 255


@router.post(
    "/tab/build-system",
    response_model=EnglishSystemTabBuildSystemResponse,
    summary="Build English System",
)
def english_system_tab_build_system(body: EnglishSystemTabBuildSystemRequest, caller_person_id: PersonId):
    """
    依 `system_tab_id` 與 `person_id` 更新該筆 English_System（deleted=false）之 **quiz_type、quiz_text、quiz_mp3_filename、quiz_youtube_url**，
    並將此四欄之值以相同鍵名合併寫入 **system_metadata**（保留既有 JSON 其他鍵，例如 `transcript/audio` 寫入之 `english_audio`）。
    `quiz_type` 未於 body 傳入時預設為 **0**（與資料表預設一致）。
    須已存在對應列（例如已呼叫 `POST /english_system/tab/create` 或 `POST /english_system/transcript/audio` 自動建列）。
    請求格式為 JSON body，對齊 `POST /rag/tab/build-rag-zip` 之「以 body 識別 tab 並寫回資料表」用法（本端點不建 RAG、不串流 NDJSON）。
    """
    fid = (body.system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(status_code=400, detail="無效的 system_tab_id")
    pid = (body.person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    if pid != caller_person_id:
        raise HTTPException(status_code=400, detail="body 的 person_id 與 query 不一致")

    mp3 = body.quiz_mp3_filename
    if mp3 is not None and len(mp3) > _VARCHAR255_MAX:
        raise HTTPException(
            status_code=400,
            detail=f"quiz_mp3_filename 長度不可超過 {_VARCHAR255_MAX}",
        )
    yt = body.quiz_youtube_url
    if yt is not None and len(yt) > _VARCHAR255_MAX:
        raise HTTPException(
            status_code=400,
            detail=f"quiz_youtube_url 長度不可超過 {_VARCHAR255_MAX}",
        )

    ts = now_taipei_iso()
    quiz_meta = {
        "quiz_type": body.quiz_type,
        "quiz_text": body.quiz_text,
        "quiz_mp3_filename": mp3,
        "quiz_youtube_url": yt,
    }

    try:
        supabase = get_supabase()
        sel = (
            supabase.table("English_System")
            .select("system_id, system_tab_id, person_id, system_metadata")
            .eq("system_tab_id", fid)
            .eq("person_id", pid)
            .eq("deleted", False)
            .limit(1)
            .execute()
        )
        if not sel.data or len(sel.data) == 0:
            raise HTTPException(
                status_code=404,
                detail="找不到該 system_tab_id 與 person_id 之 English_System，請先呼叫 POST /english_system/tab/create",
            )
        row0 = sel.data[0]
        sid = row0["system_id"]
        prev_sys = row0.get("system_metadata")
        base_meta = prev_sys if isinstance(prev_sys, dict) else {}
        merged_meta = {**base_meta, **quiz_meta}
        update_payload: dict[str, Any] = {
            **quiz_meta,
            "system_metadata": to_json_safe(merged_meta),
            "updated_at": ts,
        }
        supabase.table("English_System").update(update_payload).eq("system_id", sid).eq("deleted", False).execute()
        meta_out = to_json_safe(merged_meta)
        return EnglishSystemTabBuildSystemResponse(
            system_id=sid,
            system_tab_id=fid,
            person_id=pid,
            quiz_type=body.quiz_type,
            quiz_text=body.quiz_text,
            quiz_mp3_filename=mp3,
            quiz_youtube_url=yt,
            system_metadata=meta_out if isinstance(meta_out, dict) else None,
            updated_at=ts,
        )
    except HTTPException:
        raise
    except Exception as e:
        logging.exception("POST /english_system/tab/build-system 錯誤")
        raise HTTPException(status_code=500, detail=str(e)) from e


@router.post(
    "/tab/phase/create",
    response_model=EnglishSystemPhaseCreateLLMResponse,
    summary="Create English System Tab Phase (LLM)",
)
def create_english_system_tab_phase_with_llm(
    body: CreateEnglishSystemPhaseRequest, caller_person_id: PersonId
) -> EnglishSystemPhaseCreateLLMResponse:
    """
    以 **gpt-4o**（與 `utils.quiz_generation.generate_quiz` 相同）產題：messages **system** = **`content_text`**（教材／原文；未傳時相容 **`quiz_text`**）、**user** = **`quiz_user_prompt_instruction`**（空則預設一句）；
    LLM assistant 須回傳 JSON：`quiz_content`（題目）、`quiz_answer_reference`（參考答案或提示）。
    **請勿**呼叫 `POST /tab/phase/quiz/create` 期待 LLM（該路徑僅存草稿）。
    **回應**僅含 `system_quiz_id`（寫入之 English_System_Quiz 主鍵）、`quiz_content`、`quiz_answer_reference`。
    """
    pid = (caller_person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    fid = (body.system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(status_code=400, detail="無效的 system_tab_id")
    if body.system_id <= 0:
        raise HTTPException(status_code=400, detail="無效的 system_id")
    qname = (body.quiz_phase_name or "").strip()
    sys_src = (body.content_text or "").strip() or (body.quiz_text or "").strip()
    if not sys_src:
        raise HTTPException(
            status_code=400,
            detail="請傳入 content_text（教材／原文，作為 LLM system）；相容可傳 quiz_text",
        )
    qinstr = (body.quiz_user_prompt_instruction or "").strip()

    api_key = get_llm_api_key_for_person(pid)
    if not api_key:
        raise HTTPException(
            status_code=400,
            detail="請於使用者設定填寫 LLM API Key",
        )
    try:
        qc, qar = _english_tab_phase_llm_generate(
            content_text=sys_src,
            quiz_user_prompt_instruction=qinstr,
            api_key=api_key,
        )
        if not qc:
            raise HTTPException(status_code=502, detail="LLM 未有效回傳 quiz_content")
        if not (qar or "").strip():
            raise HTTPException(status_code=502, detail="LLM 未有效回傳 quiz_answer_reference")
        supabase = get_supabase()
        eff_tab = _validate_phase_parent_context(
            supabase, system_id=body.system_id, fid=fid, pid=pid
        )
        phase_id, _ = _upsert_english_system_phase_row(
            supabase, body=body, pid=pid, eff_tab=eff_tab, qname=qname
        )
        quiz_meta = {
            "quiz_phase_name": qname,
            "llm_model": _ENGLISH_TAB_PHASE_LLM_MODEL,
        }
        system_quiz_id = _insert_english_system_quiz_for_phase(
            supabase,
            body=body,
            pid=pid,
            eff_tab=eff_tab,
            phase_id=phase_id,
            quiz_user_prompt_instruction=qinstr,
            quiz_content=qc,
            quiz_answer_reference=qar,
            quiz_metadata=quiz_meta,
        )
        return EnglishSystemPhaseCreateLLMResponse(
            system_quiz_id=system_quiz_id,
            quiz_content=qc,
            quiz_answer_reference=qar,
        )
    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e)) from e
    except Exception as e:
        logging.exception("POST /english_system/tab/phase/create 錯誤")
        raise HTTPException(status_code=500, detail=str(e)) from e


@router.post(
    "/tab/phase/quiz/create",
    response_model=EnglishSystemPhaseCreateLLMResponse,
    summary="Create English System Tab Phase (no LLM)",
)
def create_english_system_tab_phase(
    body: CreateEnglishSystemPhaseRequest, caller_person_id: PersonId
) -> EnglishSystemPhaseCreateLLMResponse:
    """
    建立或更新 English_System_Phase（**不**呼叫 LLM）。`system_quiz_phase_id` 為 0 時新增一筆；大於 0 時更新該主鍵之列（須屬於同一 system_id、system_tab_id、person_id）。
    person_id 僅依 query（與其他 english_system API 相同）。
    若 **`quiz_content`**（題目草稿）或 **`quiz_user_prompt_instruction`** 任一非空，須同時提供 **`quiz_answer_reference`**（非空），再 insert 一筆 English_System_Quiz。
    相容：若未傳 `quiz_content` 但誤傳了 `quiz_text`，仍視為題目草稿（請改以 `quiz_content` 傳題目）。
    **回應中的 `quiz_content` 即您傳入之草稿文字，不會經過 LLM；若要把長文當教材並自動出題，請改呼叫 `POST /english_system/tab/phase/create` 並傳 `content_text`。**
    LLM 出題請用 `POST /english_system/tab/phase/create`（system=`content_text`，user=`quiz_user_prompt_instruction`）。
    僅回傳：`system_quiz_id`、`quiz_content`、`quiz_answer_reference`（無草稿時 `system_quiz_id` 為 0）。
    """
    pid = (caller_person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    fid = (body.system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(status_code=400, detail="無效的 system_tab_id")
    if body.system_id <= 0:
        raise HTTPException(status_code=400, detail="無效的 system_id")
    qname = (body.quiz_phase_name or "").strip()
    qcontent = (body.quiz_content or "").strip()
    if not qcontent:
        qcontent = (body.quiz_text or "").strip()
    qinstr = (body.quiz_user_prompt_instruction or "").strip()
    try:
        supabase = get_supabase()
        eff_tab = _validate_phase_parent_context(
            supabase, system_id=body.system_id, fid=fid, pid=pid
        )
        phase_id, _ = _upsert_english_system_phase_row(
            supabase, body=body, pid=pid, eff_tab=eff_tab, qname=qname
        )
        english_system_quiz_id: int | None = None
        qref = (body.quiz_answer_reference or "").strip()
        if qcontent or qinstr:
            if not qref:
                raise HTTPException(
                    status_code=400,
                    detail="寫入 English_System_Quiz 時 quiz_answer_reference 必填（不可為空）",
                )
            english_system_quiz_id = _insert_english_system_quiz_for_phase(
                supabase,
                body=body,
                pid=pid,
                eff_tab=eff_tab,
                phase_id=phase_id,
                quiz_user_prompt_instruction=qinstr,
                quiz_content=qcontent,
                quiz_answer_reference=qref,
                quiz_metadata=None,
            )
        sid_out = int(english_system_quiz_id or 0)
        return EnglishSystemPhaseCreateLLMResponse(
            system_quiz_id=sid_out,
            quiz_content=qcontent,
            quiz_answer_reference=qref if sid_out else "",
        )
    except HTTPException:
        raise
    except Exception as e:
        logging.exception("POST /english_system/tab/phase/quiz/create 錯誤")
        raise HTTPException(status_code=500, detail=str(e)) from e


def _validate_english_system_grade_quiz_phase(
    supabase: Any,
    *,
    english_system_id: int,
    eff_tab: str,
    person_id: str,
    english_system_quiz_phase_id: int,
    english_system_quiz_id: int,
) -> None:
    """若 english_system_quiz_phase_id／english_system_quiz_id > 0，驗證 Phase／Quiz 列與 english_system／tab／person 一致。"""
    if english_system_quiz_phase_id > 0:
        ph = (
            supabase.table("English_System_Phase")
            .select("english_system_quiz_phase_id")
            .eq("english_system_quiz_phase_id", english_system_quiz_phase_id)
            .eq("english_system_id", english_system_id)
            .eq("english_system_tab_id", eff_tab)
            .eq("person_id", person_id)
            .limit(1)
            .execute()
        )
        if not ph.data:
            raise HTTPException(
                status_code=404,
                detail="找不到符合之 English_System_Phase（請檢查 english_system_quiz_phase_id）",
            )
    if english_system_quiz_id <= 0:
        return
    r = (
        supabase.table("English_System_Quiz")
        .select(
            "english_system_quiz_id, english_system_id, english_system_tab_id, person_id, english_system_quiz_phase_id"
        )
        .eq("english_system_quiz_id", english_system_quiz_id)
        .limit(1)
        .execute()
    )
    if not r.data:
        raise HTTPException(
            status_code=404,
            detail=f"找不到 english_system_quiz_id={english_system_quiz_id} 的 English_System_Quiz",
        )
    row = r.data[0]
    if int(row.get("english_system_id") or 0) != english_system_id:
        raise HTTPException(status_code=400, detail="english_system_quiz_id 與 english_system_id 不符")
    if (row.get("english_system_tab_id") or "").strip() != eff_tab:
        raise HTTPException(status_code=400, detail="english_system_quiz_id 與 english_system_tab_id 不符")
    if (row.get("person_id") or "").strip() != person_id:
        raise HTTPException(status_code=403, detail="無權對該題評分")
    qph = row.get("english_system_quiz_phase_id")
    try:
        qph_i = int(qph) if qph is not None else 0
    except (TypeError, ValueError):
        qph_i = 0
    if english_system_quiz_phase_id > 0 and qph_i != english_system_quiz_phase_id:
        raise HTTPException(
            status_code=400,
            detail="english_system_quiz_id 所屬 phase 與 english_system_quiz_phase_id 不符",
        )


def _run_english_system_grade_llm(
    api_key: str,
    *,
    quiz_text: str,
    critique_user_prompt_instruction: str,
    quiz_content: str,
    quiz_answer: str,
) -> tuple[str, dict[str, Any]]:
    """Chat system = quiz_text；user = critique_user_prompt_instruction + 題目／作答與與 POST /rag/tab/quiz/grade 相同之 JSON 輸出規格。"""
    system_content = (quiz_text or "").strip() or "你是測驗批改助理。"
    user_instruction = (critique_user_prompt_instruction or "").strip()
    course_name = get_course_name_for_prompt()
    user_content = f"""{user_instruction}

【批改作業】
你正在批改「{course_name}」相關測驗。

【評分規範】
請根據「測驗題目」與教材／脈絡（見 system 訊息），評估「學生答案」是否正確。
測驗題目：{quiz_content}
學生答案：{quiz_answer}

【重要限制】
請使用繁體中文撰寫評語（quiz_comments 陣列中每一則）。
【評分標準】
0-5分，一定是整數（quiz_grade）。
0: 完全錯誤或未作答。
1: 只有少量內容正確。
2: 大幅缺漏，只有部分內容正確。
3: 部分正確，但有大幅缺漏。
4: 大致正確，略有不足。
5: 完全正確且完整。
【輸出 JSON】
請以 JSON 格式回傳：
{{ "quiz_grade": int,
"quiz_comments": str[] }}
"""
    client = OpenAI(api_key=api_key)
    response = client.chat.completions.create(
        model=_ENGLISH_TAB_PHASE_LLM_MODEL,
        messages=[
            {"role": "system", "content": system_content},
            {"role": "user", "content": user_content},
        ],
        response_format={"type": "json_object"},
        temperature=0.3,
    )
    llm_raw = response.choices[0].message.content or ""
    try:
        llm_json = json.loads(llm_raw)
    except json.JSONDecodeError:
        llm_json = {}
    if not isinstance(llm_json, dict):
        llm_json = {}
    _normalize_grading_llm_json(llm_json)
    return llm_raw, llm_json


def _insert_english_system_answer(
    result_dict: dict,
    quiz_answer: str,
    *,
    english_system_id: int,
    english_system_tab_id: str,
    english_system_quiz_phase_id: int,
    english_system_quiz_id: int,
    person_id: str,
) -> tuple[str, int] | None:
    """寫入 public.english_system_answer，成功回傳 ("english_system_answer_id", id)。"""
    ts = now_taipei_iso()
    row = {
        "english_system_id": english_system_id,
        "english_system_tab_id": english_system_tab_id or "",
        "english_system_quiz_phase_id": english_system_quiz_phase_id if english_system_quiz_phase_id > 0 else 0,
        "english_system_quiz_id": english_system_quiz_id if english_system_quiz_id > 0 else 0,
        "person_id": person_id or "",
        "created_at": ts,
        "updated_at": ts,
        **_answer_row_payload(result_dict, quiz_answer),
    }
    return _insert_answer_table_row("english_system_answer", "english_system_answer_id", row)


@router.post(
    "/tab/phase/quiz/grade",
    response_model=EnglishSystemQuizGradeResponse,
    summary="English System Phase Quiz Grade",
)
def english_system_tab_phase_quiz_grade(
    body: EnglishSystemQuizGradeRequest,
    caller_person_id: PersonId,
) -> EnglishSystemQuizGradeResponse:
    """
    LLM 批改（無 RAG ZIP，**同步**一次回傳）。Chat **system** = **`quiz_text`**；**user** = **`critique_user_prompt_instruction`**（並附題目、作答與與 POST `/rag/tab/quiz/grade` 一致之 JSON 評分輸出）。
    LLM API Key 依 query **person_id** 自 User 取得（與 POST `/english_system/tab/phase/create` 相同）。
    成功時寫入 english_system_answer，回傳 `quiz_grade`、`quiz_comments`、`english_system_answer_id`；寫入失敗時仍回傳分數與評語，`english_system_answer_id` 為 null。
    """
    pid = (caller_person_id or "").strip()
    if not pid:
        raise HTTPException(status_code=400, detail="請傳入 person_id")
    fid = (body.english_system_tab_id or "").strip()
    if not fid or "/" in fid or "\\" in fid:
        raise HTTPException(status_code=400, detail="無效的 english_system_tab_id")

    supabase = get_supabase()
    eff_tab = _validate_phase_parent_context(
        supabase, system_id=body.english_system_id, fid=fid, pid=pid
    )
    _validate_english_system_grade_quiz_phase(
        supabase,
        english_system_id=body.english_system_id,
        eff_tab=eff_tab,
        person_id=pid,
        english_system_quiz_phase_id=body.english_system_quiz_phase_id,
        english_system_quiz_id=body.english_system_quiz_id,
    )

    api_key = get_llm_api_key_for_person(pid)
    if not api_key:
        raise HTTPException(
            status_code=400,
            detail="該使用者（person_id）尚未於個人設定填寫 LLM API Key，請至 User 設定",
        )

    try:
        _, llm_json = _run_english_system_grade_llm(
            api_key,
            quiz_text=body.quiz_text or "",
            critique_user_prompt_instruction=body.critique_user_prompt_instruction or "",
            quiz_content=body.quiz_content or "",
            quiz_answer=body.quiz_answer or "",
        )
        result_dict: dict[str, Any] = {
            "quiz_grade": _quiz_grade_from_llm_json(llm_json),
            "quiz_comments": _quiz_comments_from_llm_json(llm_json),
        }
        inserted = _insert_english_system_answer(
            result_dict,
            body.quiz_answer or "",
            english_system_id=body.english_system_id,
            english_system_tab_id=eff_tab,
            english_system_quiz_phase_id=body.english_system_quiz_phase_id,
            english_system_quiz_id=body.english_system_quiz_id,
            person_id=pid,
        )
        aid: int | None = None
        if inserted:
            aid = inserted[1]
            _logger_grade.info(
                "English System 批改完成 english_system_answer_id=%s: %s",
                aid,
                json.dumps(result_dict, ensure_ascii=False),
            )
        else:
            _logger_grade.warning(
                "批改 LLM 已完成但寫入 english_system_answer 失敗（quiz_grade 仍回傳）",
            )
        return EnglishSystemQuizGradeResponse(
            quiz_grade=int(result_dict["quiz_grade"]),
            quiz_comments=list(result_dict.get("quiz_comments") or []),
            english_system_answer_id=aid,
        )
    except HTTPException:
        raise
    except Exception as e:
        _logger_grade.error("English System 批改失敗: %s", e, exc_info=True)
        raise HTTPException(status_code=500, detail=str(e)) from e
