-- ============================================================================
-- Quiz（試卷／Test，搭配 bank 出題）資料表 DDL
-- 定位等同 exam 之於 rag：Quiz（試卷）→ Quiz_Group（自 Bank_Group 快照）→ Quiz_QA（逐題出題／批改，無追問）。
-- 於 Supabase SQL Editor 執行；欄位對齊 Bank_Group／Bank_QA，並補上 quiz 鍵與評分欄位。
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Quiz / 試卷
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS public."Quiz" CASCADE;

CREATE TABLE public."Quiz" (
  quiz_id      bigint generated by default as identity not null,
  quiz_page_id varchar(255) not null default ''::character varying,
  person_id    varchar(255) null default ''::character varying,
  course_id    bigint null default '0'::bigint,
  tab_name     varchar(255) null default ''::character varying,
  deleted      boolean null default false,
  updated_at   timestamp without time zone null default now(),
  created_at   timestamp without time zone null default now(),
  constraint Quiz_pkey primary key (quiz_id)
) TABLESPACE pg_default;

ALTER TABLE public."Quiz" ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- Quiz_Group / 題組（自 Bank_Group 快照）
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS public."Quiz_Group" CASCADE;

CREATE TABLE public."Quiz_Group" (
  quiz_group_id                bigint generated by default as identity not null,
  quiz_page_id                 varchar(255) not null default ''::character varying,
  -- 來源 Bank 關聯（記錄此題組是從哪個 Bank_Group／單元快照而來）
  bank_page_id                 varchar(255) null default ''::character varying,
  bank_unit_id                 bigint null default '0'::bigint,
  bank_group_id                bigint null default '0'::bigint,
  person_id                    varchar(255) null default ''::character varying,
  course_id                    bigint null default '0'::bigint,
  -- 單元資訊快照
  unit_name                    varchar(255) null default ''::character varying,
  unit_type                    smallint null default '0'::smallint,
  -- 題組設定快照
  group_name                   varchar(255) null default ''::character varying,
  question_system_prompt_text  text null,
  question_user_prompt_text    text null,
  qa_count                     smallint null default '0'::smallint,
  question_llm_model           varchar(255) null default ''::character varying,
  answer_user_prompt_text      text null,
  answer_llm_model             varchar(255) null default ''::character varying,
  deleted                      boolean null default false,
  updated_at                   timestamp without time zone null default now(),
  created_at                   timestamp without time zone null default now(),
  constraint Quiz_Group_pkey primary key (quiz_group_id)
) TABLESPACE pg_default;

ALTER TABLE public."Quiz_Group" ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- Quiz_QA / 測試問答
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS public."Quiz_QA" CASCADE;

CREATE TABLE public."Quiz_QA" (
  quiz_qa_id                   bigint generated by default as identity not null,
  -- 外鍵與關聯
  quiz_group_id                bigint not null,
  quiz_page_id                 varchar(255) null default ''::character varying,
  bank_page_id                 varchar(255) null default ''::character varying,
  bank_unit_id                 bigint null default '0'::bigint,
  bank_group_id                bigint null default '0'::bigint,
  person_id                    varchar(255) null default ''::character varying,
  course_id                    bigint null default '0'::bigint,
  question_series_index        smallint null default '0'::smallint,
  -- 出題 prompt 快照（出題當下凍結；批改沿用）
  question_system_prompt_text  text null,
  question_user_prompt_text    text null,
  -- 問題（Question）
  question_content             text null,
  question_hint                text null,
  question_answer_reference    text null,
  question_reason              text null,
  question_rate                smallint null default '0'::smallint,
  question_llm_model           varchar(255) null default ''::character varying,
  -- 批改 prompt 快照 + 答案（Answer）
  answer_user_prompt_text      text null,
  answer_llm_model             varchar(255) null default ''::character varying,
  answer_content               text null,
  answer_critique              text null,
  answer_rate                  smallint null default '0'::smallint,
  deleted                      boolean null default false,
  updated_at                   timestamp without time zone null default now(),
  created_at                   timestamp without time zone null default now(),
  constraint Quiz_QA_pkey primary key (quiz_qa_id),
  constraint fk_quiz_qa_group foreign key (quiz_group_id)
    references public."Quiz_Group" (quiz_group_id) on delete cascade
) TABLESPACE pg_default;

ALTER TABLE public."Quiz_QA" ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- Quiz_Ask / 追問（出題後對題組對應之 Bank 課程內容發問，每問一列）
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS public."Quiz_Ask" CASCADE;

CREATE TABLE public."Quiz_Ask" (
  quiz_ask_id          bigint generated by default as identity not null,
  -- 外鍵與關聯
  quiz_group_id        bigint not null,
  quiz_page_id         varchar(255) null default ''::character varying,
  bank_page_id         varchar(255) null default ''::character varying,
  bank_unit_id         bigint null default '0'::bigint,
  bank_group_id        bigint null default '0'::bigint,
  person_id            varchar(255) null default ''::character varying,
  course_id            bigint null default '0'::bigint,
  -- 單元與題組資訊快照
  unit_name            varchar(255) null default ''::character varying,
  unit_type            smallint null default '0'::smallint,
  group_name           varchar(255) null default ''::character varying,
  -- 追問與回覆內容
  ask_user_prompt_text text null,
  answer_content       text null,
  answer_rate          smallint null default '0'::smallint,
  deleted              boolean null default false,
  -- 時間戳記
  updated_at           timestamp without time zone null default now(),
  created_at           timestamp without time zone null default now(),
  constraint Quiz_Ask_pkey primary key (quiz_ask_id),
  constraint fk_quiz_ask_group foreign key (quiz_group_id)
    references public."Quiz_Group" (quiz_group_id) on delete cascade
) TABLESPACE pg_default;

ALTER TABLE public."Quiz_Ask" ENABLE ROW LEVEL SECURITY;
