-- Quiz 表 schema（在 Supabase 後台：SQL Editor → 貼上整段 → Run）
-- 如果 public."Quiz" 已經存在，則強制刪除它（包含依賴它的關聯）
DROP TABLE IF EXISTS public."Quiz" CASCADE;

-- 重新建立資料表
CREATE TABLE public."Quiz" (
  -- 【主鍵欄位】集中放置於最前方
  quiz_id bigint generated by default as identity not null,
  rag_id bigint generated by default as identity not null,

  -- 【其他一般欄位】
  file_id varchar(255) not null default ''::character varying,
  person_id varchar(255) null default ''::character varying,
  course_name varchar(255) null default ''::character varying,
  system_prompt_instruction varchar(1000) null default ''::character varying,
  rag_name varchar(255) null default ''::character varying,
  quiz_level varchar(64) null default ''::character varying,
  quiz_content text null default ''::character varying,
  quiz_hint text null default ''::character varying,
  reference_answer text null default ''::character varying,
  quiz_metadata json null,
  quiz_type smallint null default '0'::smallint,
  updated_at timestamp without time zone null default now(),
  created_at timestamp without time zone null default now(),

  -- 設定複合主鍵
  constraint Quiz_pkey primary key (quiz_id, rag_id)
) TABLESPACE pg_default;

-- 啟用 RLS (Row Level Security)
ALTER TABLE public."Quiz" ENABLE ROW LEVEL SECURITY;
