-- Rag_Answer 表 schema（在 Supabase 後台：SQL Editor → 貼上整段 → Run）
-- 如果 public."Rag_Answer" 已經存在，則強制刪除它（包含依賴它的關聯）
DROP TABLE IF EXISTS public."Rag_Answer" CASCADE;

-- 重新建立資料表
CREATE TABLE public."Rag_Answer" (
  -- 【主鍵欄位】集中放置於最前方
  rag_answer_id bigint generated by default as identity not null,

  -- 【其他一般欄位】
  rag_quiz_id bigint not null default 0,
  rag_id bigint not null default 0,
  rag_tab_id varchar(255) null default ''::character varying,
  person_id varchar(255) null default ''::character varying,
  course_name varchar(255) null default ''::character varying,
  rag_name varchar(255) null default ''::character varying,
  student_answer text null default ''::character varying,
  answer_grade smallint null default 0,
  answer_feedback_metadata text null default ''::character varying,
  answer_metadata json null,
  updated_at timestamp without time zone null default now(),
  created_at timestamp without time zone null default now(),

  -- 設定主鍵
  constraint Rag_Answer_pkey primary key (rag_answer_id)
) TABLESPACE pg_default;

-- 啟用 RLS (Row Level Security)
ALTER TABLE public."Rag_Answer" ENABLE ROW LEVEL SECURITY;
