-- Rag 表 schema（在 Supabase 後台：SQL Editor → 貼上整段 → Run）
-- 如果 public."Rag" 已經存在，則強制刪除它（包含依賴它的關聯）
DROP TABLE IF EXISTS public."Rag" CASCADE;

-- 重新建立資料表
CREATE TABLE public."Rag" (
  -- 【主鍵欄位】集中放置於最前方
  rag_id bigint generated by default as identity not null,

  -- 【其他一般欄位】
  file_id varchar(255) not null default ''::character varying,
  person_id varchar(255) null default ''::character varying,
  name varchar(255) null default ''::character varying,
  course_name varchar(255) null default ''::character varying,
  llm_api_key varchar(255) null default ''::character varying,
  file_metadata json null,
  rag_list varchar(1000) null default ''::character varying,
  system_prompt_instruction varchar(1000) null default ''::character varying,
  rag_metadata json null,
  chunk_size smallint null default '0'::smallint,
  chunk_overlap smallint null default '0'::smallint,
  applied boolean null default false,
  deleted boolean null default false,
  updated_at timestamp without time zone null default now(),
  created_at timestamp without time zone null default now(),

  -- 設定主鍵
  constraint Rag_pkey primary key (rag_id)
) TABLESPACE pg_default;

-- 啟用 RLS (Row Level Security)
ALTER TABLE public."Rag" ENABLE ROW LEVEL SECURITY;
