-- Test / Quiz / Answer 表 schema（在 Supabase 後台：SQL Editor → 貼上整段 → Run）
-- 對應 API：POST /test/create-test, /test/generate-quiz, /test/quiz-grade

-- 如果 public."Test" 已經存在，則強制刪除它（包含依賴它的關聯）
DROP TABLE IF EXISTS public."Test" CASCADE;

-- 重新建立資料表
CREATE TABLE public."Test" (
  -- 【主鍵欄位】集中放置於最前方
  test_id bigint generated by default as identity not null,
  
  -- 【其他一般欄位】
  test_tab_id varchar(255) not null default ''::character varying,
  person_id varchar(255) null default ''::character varying,
  test_name varchar(255) null default ''::character varying,
  deleted boolean null default false,
  updated_at timestamp without time zone null default now(),
  created_at timestamp without time zone null default now(),
  
  -- 設定複合主鍵
  constraint Test_pkey primary key (test_id)
) TABLESPACE pg_default;

-- 啟用 RLS (Row Level Security)
ALTER TABLE public."Test" ENABLE ROW LEVEL SECURITY;


-- 如果 public."Quiz" 已經存在，則強制刪除它（包含依賴它的關聯）
DROP TABLE IF EXISTS public."Quiz" CASCADE;

-- 重新建立資料表
CREATE TABLE public."Quiz" (
  -- 【主鍵欄位】集中放置於最前方
  quiz_id bigint generated by default as identity not null,

  -- 【其他一般欄位】
  rag_id bigint not null default 0,
  tab_id varchar(255) not null default ''::character varying,
  person_id varchar(255) null default ''::character varying,
  course_name varchar(255) null default ''::character varying,
  system_prompt_instruction varchar(1000) null default ''::character varying,
  rag_name varchar(255) null default ''::character varying,
  quiz_level smallint null default '0'::smallint,
  quiz_content text null default ''::character varying,
  quiz_hint text null default ''::character varying,
  reference_answer text null default ''::character varying,
  quiz_metadata json null,
  quiz_type smallint null default '0'::smallint,
  updated_at timestamp without time zone null default now(),
  created_at timestamp without time zone null default now(),

  -- 設定複合主鍵
  constraint Quiz_pkey primary key (quiz_id)
) TABLESPACE pg_default;

-- 啟用 RLS (Row Level Security)
ALTER TABLE public."Quiz" ENABLE ROW LEVEL SECURITY;

-- Answer 表 schema（在 Supabase 後台：SQL Editor → 貼上整段 → Run）
-- 如果 public."Answer" 已經存在，則強制刪除它（包含依賴它的關聯）
DROP TABLE IF EXISTS public."Answer" CASCADE;

-- 重新建立資料表
CREATE TABLE public."Answer" (
  -- 【主鍵欄位】集中放置於最前方
  answer_id bigint generated by default as identity not null,

  -- 【其他一般欄位】
  quiz_id bigint not null default 0,
  rag_id bigint not null default 0,
  tab_id varchar(255) null default ''::character varying,
  person_id varchar(255) null default ''::character varying,
  course_name varchar(255) null default ''::character varying,
  rag_name varchar(255) null default ''::character varying,
  student_answer text null default ''::character varying,
  answer_grade smallint null default 0,
  answer_feedback_metadata text null default ''::character varying,
  answer_metadata json null,
  updated_at timestamp without time zone null default now(),
  created_at timestamp without time zone null default now(),

  -- 設定主鍵
  constraint Answer_pkey primary key (answer_id)
) TABLESPACE pg_default;

-- 啟用 RLS (Row Level Security)
ALTER TABLE public."Answer" ENABLE ROW LEVEL SECURITY;
