-- Exam_Quiz 資料表 schema（rag_name 改為 rag_id）
-- 如果 public."Exam_Quiz" 已經存在，則強制刪除它（包含依賴它的關聯）
DROP TABLE IF EXISTS public."Exam_Quiz" CASCADE;

-- 重新建立資料表
CREATE TABLE public."Exam_Quiz" (
  -- 【主鍵欄位】集中放置於最前方
  exam_quiz_id bigint generated by default as identity not null,

  -- 【其他一般欄位】
  exam_id bigint not null default 0,
  exam_tab_id varchar(255) not null default ''::character varying,
  person_id varchar(255) null default ''::character varying,
  rag_id bigint not null default 0,
  quiz_level smallint null default '0'::smallint,
  quiz_content text null default ''::character varying,
  quiz_hint text null default ''::character varying,
  reference_answer text null default ''::character varying,
  quiz_metadata json null,
  updated_at timestamp without time zone null default now(),
  created_at timestamp without time zone null default now(),

  -- 設定複合主鍵
  constraint Exam_Quiz_pkey primary key (exam_quiz_id)
) TABLESPACE pg_default;

-- 啟用 RLS (Row Level Security)
ALTER TABLE public."Exam_Quiz" ENABLE ROW LEVEL SECURITY;
