-- LLM API Key 表：user 可填入自己的 API Key
DROP TABLE IF EXISTS public."LLM_API_Key" CASCADE;

CREATE TABLE public."LLM_API_Key" (
  llm_api_key_id bigint generated by default as identity not null,
  person_id varchar(255) not null default ''::character varying,
  llm_api_key varchar(255) null default ''::character varying,
  updated_at timestamp without time zone null default now(),
  created_at timestamp without time zone null default now(),

  constraint LLM_API_Key_pkey primary key (llm_api_key_id)
) TABLESPACE pg_default;

ALTER TABLE public."LLM_API_Key" ENABLE ROW LEVEL SECURITY;
